### ISSUE TITLE
It's possible to cause wifi to go into an endless loop if passphrase is too long

### ISSUE THREAD

**Issue by fredriksvantes** [dappnode/DNP_DAPPMANAGER#1024]
**Describe the bug**

WPA passphrases may be 8..63 characters long. Dappnode GUI allows to set a passphrase that is >63 characters. If this is done, the wifi module will not start but instead go into an endless loop until changed to something within the bounds of WPA.

**DAppNode version:**
Last version

**Comment by pablomendezroyo** [comment]
Thanks for the report!

We should replicate the error and strongly determine the maximum length of the password and set the maximum password length at https://github.com/dappnode/DNP_DAPPMANAGER/blob/18386a7b2abf0d9da1816b442be30f2cfd1b3a26/packages/admin-ui/src/utils/validation.ts#L29

**Comment by alexpeterson91** [comment]
PR draft created.

**Comment by alexpeterson91** [comment]
@pablomendezroyo Confirmed 63 is max characters for WPA standard, implemented check and front end warning and baked it into the validation function making it not possible to exceed 63 characters so this issue cannot occur again, PR #1026 appears to fix it netlify shows proper use and that it works as expected.  only unverified commit was a typo initially. It's awaiting review now
