### ISSUE TITLE
Exposable HTTPS by default not working properly

### ISSUE THREAD

**Issue by mgarciate** [dappnode/DNP_DAPPMANAGER#1040]
**Describe the bug**

I created a package with a port exposable by default with the following entry in dappnode_package.json:
```json
"exposable": [
    {
      "name": "Expose Pocket RPC",
      "description": "Expose Pocket RPC",
      "serviceName": "pocket",
      "port": 8081,
      "exposeByDefault": true
    }
  ]
```

The service in the docker-compose.yml looks like:

```
version: "3.4"
services:
  pocket:
    image: "pocket.pocket.dnp.dappnode.eth:0.1.0"
    build:
      context: pocket
```

The installation creates the public URL `pocket-pocket.xxxxx.dyndns.dappnode.io` and also `Pocket.xxxxx.dyndns.dappnode.io` which is wrong and could make it unable to install or update the package again.

**To Reproduce**

1. Compile the package with the command: `npx @dappnode/dappnodesdk build`
2. Install the package
3. Check the exposed port at http://my.dappnode/#/system/network
4. See that the exposed url is `https://Pocket.xxxxx.dyndns.dappnode.io` instead of `https://pocket-pocket.xxxxx.dyndns.dappnode.io`
5. "Unexpose" the HTTPS entry and expose it again
6. See that the exposed url is `https://pocket-pocket.xxxxx.dyndns.dappnode.io`

**Expected behavior**

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/7695193/173500110-780021e0-348a-4e36-bc4d-d80b36a45c55.png">

**Screenshots**

Current behaviour after installing:
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/7695193/173503307-884d4053-b235-4a39-9802-00417d7fd8f4.png">
And the Network tab into the package:
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/7695193/173503432-11f59370-8220-47a1-b962-82ad2683f224.png">

**DAppNode version:**

- core.dnp.dappnode.eth: 0.2.55
- dappmanager.dnp.dappnode.eth: 0.2.50, commit: 552ab6c8
- https.dnp.dappnode.eth: 0.1.3

**Additional context**

**Comment by pablomendezroyo** [comment]
The issue seems to be the docs outdated. The current types for exposable is
``` 
interface ExposableServiceManifestInfo {
  name: string;
  description?: string;
  serviceName?: string;
  fromSubdomain?: string;
  port: number;
  exposeByDefault?: boolean;
}
``` 

@tropicar could you review the docs and make sure it is up to date?

**Comment by tropicar** [comment]
https://docs.dappnode.io/developers/manifest-reference#exposable
The property that is not updated is:
`fromSubdomain?: string;`

I will add it in the docs.

**Comment by pablomendezroyo** [comment]
@tropicar also `exposeByDefault`

This process should be manual but automatically update de docs according to the manifest and wizard schemas
