### ISSUE TITLE
Use SDK as a dependency

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1041]
**Context**
Due to the recent improvement and implementations of the validation for the release files in the SDK, use the SDK as a dependency to avoid code duplication

**Approach**
- [x] Use `setupWizard`, `manifest` and `compose` types from SDK, delete the ones in the dappmanager and make sure are the same and does not break anything https://github.com/dappnode/DNP_DAPPMANAGER/pull/1049
- [ ] Use `dappnodeDefaults` from the SDK to set the default values during the package installation. Deppends on https://github.com/dappnode/DAppNodeSDK/issues/235
- [x] Use validation release files (schemas and dappnode requirements) for `setupWizard`, `manifest` and `compose` and remove the current validation https://github.com/dappnode/DNP_DAPPMANAGER/pull/1078

**Comment by dapplion** [comment]
@pablomendezroyo The SDK should just export simple functions like
```
function validateCompose(compose: Compose): void {}
```
That either return a list of errors or throw

**Comment by pablomendezroyo** [comment]
Implemented
