### ISSUE TITLE
Change full node repository 

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#1050]
**Is your feature request related to a problem? Please describe.**

OpenEthereum will be deprecated after the merge in Ethereum. Erigon package is almost fixed(only it's needed to merge the PR and publish the latest version).

**Describe the solution you'd like**

We have to remove the OpenEthereum option as a client in the wizard(the first time a user access the dappnode) and add Erigon client.

**Comment by pablomendezroyo** [comment]
Openethereum removed from repository options
