### ISSUE TITLE
Set default resource usage limits

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#1052]
**Is your feature request related to a problem? Please describe.**

As we have seen recently with nethermind, a bug in software may result in whole DAppNode crashing.
**Describe the solution you'd like**

During parsing of docker compose, if not found, DAppManger should inject default resource limits on (at least) CPU and memory.

**Additional context**

This will prevent single faulty package crashing whole system.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/1078
