### ISSUE TITLE
Detect if system needs to be restarted and prompt user to do so

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#1053]
After certain updates (i.e. kernel), a system restart is needed for those updates to take effect. This is important because those updates may be security related.  
DAppManager should: 
* detect that restart is needed 
* prompt user to do restart

I think the best way to acomplish this is to be anoying and have prompt to the effect "Restart will happen in x, click to restart now or postpone it".

**Comment by 3alpha** [comment]
Just noting that we need to inspect value `needrestart -b | grep NEEDRESTART-KSTA | cut -d' ' -f2`

**Comment by pablomendezroyo** [comment]
Implemented! 🚀
