### ISSUE TITLE
Migration from openethereum users to another client

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#1055]
**Is your feature request related to a problem? Please describe.**

The file migrateEthchain.ts use an old feature to instal the client. In this file appears openethereum references and this function is executed by the dappmanager in the index. 
We should discuss how we are dealing with the users currently using openEthereum client.

**Describe the solution you'd like**
We should discuss this topic in devs meeting. I dont have an idea to solve this. But we should talk about :
1. Will we change the user client from openethereum to another with no ask? this does not seem the best solution.
2. Can we ask the users when they update the dappmanager?

**Additional context**

OpenEthereum Client will be deprecated when the merge happens, even this client will not be prepared for the merge, so its very important to retire this client option as soon as possible.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/1056 and https://github.com/dappnode/DNP_DAPPMANAGER/pull/1059
