### ISSUE TITLE
Add telegram notification in the migration to openweb3igner

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#1060]
**Is your feature request related to a problem? Please describe.**

The objective is to offer to the user more ways to receive notifications related to the validators

**Describe the solution you'd like**

Using the telegram daemon we have in dappmanager, checking every X time the next stuff:
- Check if the web3signer(gnosis/prater) and the selected client are running, if it's not show a danger notification.
- Check if the selected client is syncing or is synced. If its syncing shows a warning notification.

**Describe alternatives you've considered**

If we have more time, maybe we could use the eventBus notifications instead of doing all this set-up in telegram only.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/1062
