### ISSUE TITLE
Split the `EthClientTarget` to handle EL and CL

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1094]
With The Merge, `EthClientTarget` has been set by the user and must be edited to contemplate the combinations of EL + CL and remote. 

It should go from 
``` 
export type EthClientTargetPackage = "geth-light" | "geth" | "nethermind";
export type EthClientTarget = EthClientTargetPackage | "remote";
```
to
```
export type ExecutionClientTargetPackage = "geth-light" | "geth" | "nethermind";
export type ConsensusClientTargetPackage = "prysm" | "nimbus" | "lighthouse" | "teku"

interface CustomEthClientTarget {
  executionClient: ExecutionClientTargetPackage;
  consensusClient: ConsensusClientTargetPackage;
}

export type EthClientTarget = CustomEthClientTarget | "remote";
```

Deppends on DAppNode infra node to serve EL + CL  @3alpha

**Comment by 3alpha** [comment]
Does this split make sense? After the merge, local execution layer cannot use remote consensus and vice-versa. So you have to have either both clients or none. I think. 🤔

**Comment by pablomendezroyo** [comment]
Thats why the type is `custom` or `remote`
```
export type EthClientTarget = CustomEthClientTarget | "remote";
```

**Comment by pablomendezroyo** [comment]
ping @3alpha agree?

Related with https://github.com/dappnode/DNP_DAPPMANAGER/issues/1149

**Comment by 3alpha** [comment]
I agree.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/issues/1149
