### ISSUE TITLE
Timeout to find a package in IPFS probably not enough

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#111]
When you try to install a package recently uploaded to IPFS, via an IPFS hash, the installer gives back "Package not found", when you reload and try again, it works

**Comment by dapplion** [comment]
The IPFS timeout was increased from 3 seconds to 30 seconds in the last release. Is this issue still persisting? @Shelpin  Let me know if you can re-test it

**Comment by Shelpin** [comment]
Great thanks !!!! it should not happen again, still when i am together with Edu we will make this test  again, currently i do not have  any package that has been just uploaded to IPFS to test. Closing the issue as the timeout is already increased. Thanks!
