### ISSUE TITLE
Add Besu as an official Repo Client and Merge Ready Client

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DNP_DAPPMANAGER#1116]
Besu must be added to the EL client selection to mitigate the new issue of low client diversity on the execution layer, now that Geth had a major bug recently and nethermind is the only other option since OE has been deprecated and Erigon is not yet stable enough.

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/1158
