### ISSUE TITLE
Remove Volumes of Core Packages not working 

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#112]
Hi!! just seeing how the node was synchronising to make sure that after the warp it went for the full sync, and realized that the synchronization was stuck in block 57. I wanted to remove the volume so the chain started syncing again, but the button is performing no action when clicked, the same happens with other core packages  as IPFS. This test has been made also in our current release  and also happens, it seems it is not a matter of the last update  of VPN, ADMIN and DAPPMANAGER

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/87bf7bb0b9a22b892b3364aa793b4d400bfd3f1c

**Comment by dapplion** [comment]
@Shelpin Please for issues that are not identical to the new issue it's always best to open a new issue. The issue you are mentioning should be openned in the DNP_ADMIN repo and be something like "Add a delete confirmation for..." as an enhancement request. Thank you!

**Comment by Shelpin** [comment]
Sorry man !! doing it right now!!
