### ISSUE TITLE
Add Erigon as official fullnode repo client

### ISSUE THREAD

**Issue by alexpeterson91** [dappnode/DNP_DAPPMANAGER#1123]
Erigon should be added as a fullnode option for a repo client, currently only geth and nethermind are options.  
let me know if theres a reason this wasnt done already?

**Comment by pablomendezroyo** [comment]
Erigon was not stable enough, not sure if this situation has changed

**Comment by alexpeterson91** [comment]
Keeping this open for stalebot

**Comment by tropicar** [comment]
We should add it. But the size of erigon is huge, it would good idea to mention it, it occupies around 2 TB.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/1158
