### ISSUE TITLE
No options selected in stakers ui provoke error on packages page

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#1141]
**Describe the bug**

If you dont define any value on stakers UI and you go to packages the packages page shows an error.

**To Reproduce**

Steps to reproduce the behaviour:
1. Remove and disable all the option of the stakers-ui and click apply button
2. go to packages 

**Expected behaviour**

All are removed and packages show the package you have installed

**Screenshots**

![Screenshot from 2022-09-30 10-15-34](https://user-images.githubusercontent.com/59098811/193225742-94da6d84-63a5-4272-8d61-231180f27422.png)

**Comment by pablomendezroyo** [comment]
I have not been able to reproduce the error.

Could you share the error details?

**Comment by pablomendezroyo** [comment]
@tropicar ping

**Comment by tropicar** [comment]
I do have not more information, i had to reset the machine. But this error did not appear again.
