### ISSUE TITLE
_DAPPNODE_GLOBAL_EXECUTION_CLIENT_PRATER causes the inability to install packages

### ISSUE THREAD

**Issue by mgarciate** [dappnode/DNP_DAPPMANAGER#1144]
**Describe the bug**

`_DAPPNODE_GLOBAL_EXECUTION_CLIENT_PRATER` causes the inability to install packages that make use of globalEnvs.
Check _Additional context_ below

> Error: Command failed: docker-compose -f /usr/src/app/dnp_repo/pocket.dnp.dappnode.eth/docker-compose.yml up --no-start --remove-orphans <&-
> Container DAppNodePackage-pocket.pocket.dnp.dappnode.eth  Creating
> Error response from daemon: invalid environment variable: =_DAPPNODE_GLOBAL_EXECUTION_CLIENT_PRATER
> 
>     at /usr/src/app/webpack:/@dappnode/dappmanager/src/utils/shell.ts:35:16
>     at Generator.throw (<anonymous>)
>     at rejected (/usr/src/app/index.js:400143:65)
>     at runMicrotasks (<anonymous>)
>     at processTicksAndRejections (node:internal/process/task_queues:96:5)

**To Reproduce**

Steps:

1. Fresh install of DAppNode
3. Install a package that uses the globalEnvs such us Store or Pocket
5. Cannot install the package

**Expected behavior**

The package should be installed

**Screenshots**

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/7695193/194694816-daf788ae-4424-4f00-a1d2-d422c691b200.png">

**DAppNode version:**

bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.58
dappmanager.dnp.dappnode.eth: 0.2.53, branch: develop, commit: 45ec898e
https.dnp.dappnode.eth: 0.1.3
ipfs.dnp.dappnode.eth: 0.2.18
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.1

**Additional context**

You can install the package if you previously install an Execution client and a Consensus client from the new Stakers UI.
It also happens after removing the Execution client and the Consensus client

**Comment by tropicar** [comment]
I could solve this error by removing the global env from the manifest of the package you are trying to install for now, but it's true that the error appears. I suggest removing it because the only package that uses global envs are prater packages.

**Comment by alexpeterson91** [comment]
SSV Shifu will be needing to use the global envs too but just needs to read them not change them etc. Needs WS 8546 from EL and beacon chain gateway at 3500 no need for jwt or the apiEngine. Right now it's manual selection and with the stakers UI it won't work that well without global envs included in the ssv shifu package.

**Comment by pablomendezroyo** [comment]
I have not been able to reproduce the error, which dappmanager version are you running?

I have successfully installed the Pocket package available in the dappstore wich uses the `globalEnvs: {all: true}`

**Comment by alexpeterson91** [comment]
> I have not been able to reproduce the error.

neither could I for a long time but i have had dozens of support cases due to this.  I finally was able to reproduce it trying to install Pokt on a fresh install.  I ended up changing the package to fix an issue with the Erigon Implementation, and when i tried installing it to test, it installed perfectly.  Never had it happen again installing anything else

**Comment by mgarciate** [comment]
> I have not been able to reproduce the error, which dappmanager version are you running? It could be related to an outdated dappmanager version. If this is the bug, adding the `minimumDappnodeVersion` to the manifest would save users and force them to update the dappnode before installing the package
> 
> I have successfully installed the Pocket package available in the dappstore wich uses the `globalEnvs: {all: true}`

I did a fresh install of DAppNode

**Comment by alexpeterson91** [comment]
I did a fresh install as well to provoke the error. Used the latest ISO install.

**Comment by pablomendezroyo** [comment]
Global envs must be used exclusively by those packages that will use them. Using `globalEnvs` as `{all: true}` will be deprecated, see https://github.com/dappnode/DAppNodeSDK/pull/270

Instead of using `{all: true}` define the globalEnv to be used by each service, see https://github.com/dappnode/DAppNodePackage-pokt/pull/13

This looks like other issue, which does not allow to install a package that defines a globalEnv that is not set https://github.com/dappnode/DNP_DAPPMANAGER/issues/1150
