### ISSUE TITLE
Wireguard - "Download config" always downloads REMOTE file. Even when switched to LOCAL

### ISSUE THREAD

**Issue by Cryptooly** [dappnode/DNP_DAPPMANAGER#1145]
**Describe the bug**

VPN page, wireguard tab (http://my.dappnode/#/vpn/wireguard -> click on "Get link" of one of the credential names)

There are three buttons: "Download xxx config", "Copy xxx config" and "Show xxx config QR code" where xxx is "local" or "remote".

Then there is the link which switches between "local" and "remote" config

Regardless of that local/remote state, the first button ("Download xxx config") ALWAYS downloads the **remote** config file. 
**Even when switched to "local" it will download the "remote" one.** 
(The other two buttons seem to respect the state correctly)

**To Reproduce**

Just try the steps above to reproduce.

**Expected behavior**

Expected would be to download the "local" config file when the state is set to "local".

**Screenshots**
![image](https://user-images.githubusercontent.com/105727883/194760032-e94868c8-d7bc-4f8e-968d-55117224c87e.png)

**DAppNode version:**

bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.58
dappmanager.dnp.dappnode.eth: 0.2.53, branch: develop, commit: 45ec898e
https.dnp.dappnode.eth: 0.1.3
ipfs.dnp.dappnode.eth: 0.2.18
wifi.dnp.dappnode.eth: 0.2.8
wireguard.dnp.dappnode.eth: 0.1.1

**Comment by pablomendezroyo** [comment]
Thanks for the report! fixed by https://github.com/dappnode/DNP_DAPPMANAGER/commit/9a4c194b0e4fea487ac92509630cfca4a113c3e4
