### ISSUE TITLE
Implement onboarding process in stakers UI

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1219]
Set up an onboarding view (allow to execute the onboarding with a button) in the stakers UI with the following steps:
1. Generate validator keystores
2. Select execution client
3. Select consensus client (graffiti, checkpointsync and fee recipient address)
5. Activate/deactivate signer
6. Activate/deactivate mev boost (and relays)

**Comment by dsimog01** [comment]
It should be both shown when you first access the stakers UI and also when you click a "Getting started" button.
