### ISSUE TITLE
Implement featured cards for mainnet and gnosis

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1226]
If staker package (execution client, consensus client, signer, mev boost) ENS is about to be installed from the normal installer view redirect to stakers UI

**Update**
- [x] Implement featured fake cards for gnosis and mainnet stakers
- [x] Redirect users when clicking on featured fake cards to stakers UI, gnosis or mainnet
- [ ] Upload logos hashes for ethereum and gnosis and pin them with dappnode infra

**Comment by alexpeterson91** [comment]
Why?

**Comment by pablomendezroyo** [comment]
> Why?

Sorry, only for staker packages

**Comment by pablomendezroyo** [comment]
Also consider adding a fake package car for "stakers" that redirects to the stakers UI
