### ISSUE TITLE
Allow to change the Ethereum repository remote URL

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1245]
When users use the Ethereum repository remote option, they are obligated to use the dappnode remote Eth node `web3.dappnode.net`.

Implement an input with the default value of the dappnode remote node, allowing to change the Eth node to be used as remote option.

**Comment by dappnodedev** [comment]
A more detailed explanation:

In the Ethereum repository view, a user can switch between their own Ethereum full node and the Dappnode official Ethereum node (web3.dappnode.net):

![image](https://github.com/dappnode/DNP_DAPPMANAGER/assets/144998261/2d06ea72-9480-41a4-ab56-e905b887ff1d)

But we would like the user to choose any Ethereum node URL here, similarly to what we have for the IPFS remote repository:

![image](https://github.com/dappnode/DNP_DAPPMANAGER/assets/144998261/13d08d2d-6976-4216-9559-ccea1b58e56f)

**Comment by pablomendezroyo** [comment]
Implemented 🚀  !
