### ISSUE TITLE
Avoiding machines to become "useless" when disk is full

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#125]
When a DAppnode´s disk gets full you can`t do anything anymore with it...

**Comment by dapplion** [comment]
@Shelpin Thanks for reporting. We will consider automatically stopping all the containers if the disk space becomes too full. Moving to backlog

**Comment by Shelpin** [comment]
Tried it and works!!! great! still when the machine goes disk full , it is bit annoying in chrome, as  metamask browser jumps in and allows almost no time to remove any of the packages, i had to do it with safari, if navigating  with chrome would be convenient  to  warn users about removing  packages with a non metamask browser, or being  damned  fast going to packages, bitcoin,remove + data ;), can be a nice game  ;). Also the notification about the stop  of  every service   disappears when refreshing, maybe it should last until the disk  is not  near 100%
