### ISSUE TITLE
When you install a package you can´t see anymore where is it installed

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#126]

**Comment by dapplion** [comment]
@Shelpin Please can you provide a more accurate description of the issue?

**Comment by Shelpin** [comment]
OFC!!Sorry for the briefness... I mean that when you are going to install a package you see the path  where  it is gonna be installed and  can edit it to choose the volume, but once it is installed you do not have a way in the ADmin UI to know in which path has that package been installed.... what could be needed if you want to perform any action  in that  package through the terminal i.e, you can always look  for it manually, but i was wondering if this could be a useful information to be provided in the package info

**Comment by dapplion** [comment]
Of course, great suggestion! I will develop a solution for this issue in the DNP_ADMIN repo. Closing this issue which is replaced by https://github.com/dappnode/DNP_ADMIN/issues/151
