### ISSUE TITLE
Add new gnosis and ultrasound.monet relayers to MEV Boost

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#1278]
Official announcement:

https://twitter.com/GnosisDAO/status/1597940022660894721?s=20&t=ShexF9w8MEvKxhKPtU3u0g

we need to add this two new relayers to the MEV-BOOST Mainnet stakers UI:

https://agnostic-relay.net/
https://relay.ultrasound.money/

**Comment by dsimog01** [comment]
Merged in https://github.com/dappnode/DNP_DAPPMANAGER/pull/1282
