### ISSUE TITLE
Implement a dedicated view for dappnode repository

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1286]
The repository in dappnode (either IPFS or Ethereum) is a crucial part of the dappnode for its functionality. Consider developing a dedicated view in the menu for "repository". This view should have 2 sub-tabs: IPFS and Ethereum. In each sub-tab there should be:
- Possibility to switch from remote to local and viceversa
- Health checker 
- ?

**Comment by dsimog01** [comment]
Move the settings>repository view to an own tab on the left menu. Also try to improve its view.

**Comment by dsimog01** [comment]
This is handled in PR: https://github.com/dappnode/DNP_DAPPMANAGER/pull/1327
