### ISSUE TITLE
Packages appear as crashed after being stopped

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DNP_DAPPMANAGER#1300]
When stopping packages manually or through the stakers UI, they sometimes appear as "crashed" instead of "stopped". This might have to do with a docker timeout that is too low to allow the packages stop gracefully.

**Comment by dsimog01** [comment]
The packages that usually appear as CRASHED are: Teku

**Comment by pablomendezroyo** [comment]
This is a expected behaviour, it should be instead implemented the docker timeout feature
