### ISSUE TITLE
SIze 0 updates

### ISSUE THREAD

**Issue by dsimog01** [dappnode/DNP_DAPPMANAGER#1302]
Sometimes updates show 0MB size. We still do not know when this happens. It has just happened to me with IPFS remote, but changing to remote did not solve it.

Despite showing 0MB, the update is performed correctly.

**Comment by alexpeterson91** [comment]
Happens to me pretty regularly now too. But some nodes are all size zero. Some are just certain packages in my experience.

**Comment by pablomendezroyo** [comment]
Duplicate
