### ISSUE TITLE
High CPU consumption on v0.2.59

### ISSUE THREAD

**Issue by mfw78** [dappnode/DNP_DAPPMANAGER#1335]
**Describe the bug**

After updating to version 0.2.59, the dappnode incurs significant CPU usage. This manifests in slow to access API functionality (stakers takes a long time to load), packages failing to install, as well as measurable increases in CPU usage, as measured from DMS.

This has been verified to be an issue across two dappnodes, to rule out any configuration dependent problems.

**To Reproduce**

1. Install version 0.2.59
2. Use dappnode

**Expected behavior**

1. Prompt, snappy UI.
2. CPU usage is not nearly 25% of CPU.

**Screenshots**

Container CPU usage, last 24 hrs:

![image](https://user-images.githubusercontent.com/53399572/209615778-a04ca11e-c341-49c0-8f42-1d2dd58c04a7.png)

Container CPU usage, last 7 days:

![image](https://user-images.githubusercontent.com/53399572/209615822-610e3188-3d25-4dcf-a700-70bb90d194ae.png)

Container CPU usage, last 30 days:

![image](https://user-images.githubusercontent.com/53399572/209615915-eb18b413-8f64-4cfe-88e9-e0d046a2406b.png)

**DAppNode version:**

```
Core DAppNode Packages versions
    bind.dnp.dappnode.eth: 0.2.6
    core.dnp.dappnode.eth: 0.2.64
    dappmanager.dnp.dappnode.eth: 0.2.59, commit: 26522964
    https.dnp.dappnode.eth: 0.1.4
    ipfs.dnp.dappnode.eth: 0.2.18
    wifi.dnp.dappnode.eth: 0.2.8
    wireguard.dnp.dappnode.eth: 0.1.2

System info
    dockerComposeVersion: 1.25.5
    dockerServerVersion: 20.10.6
    dockerCliVersion: 20.10.6
    os: debian
    versionCodename: bullseye
    architecture: amd64
    kernel: 5.10.0-9-amd64
    Disk usage: 76%
```

**Additional context**

It would be great to be able to rollback.

**Comment by mfw78** [comment]
On another node, since upgrade, this is manifesting in the entire dappnode core containers becoming unusable. They constantly require a `dappnode_stop` and `dappnode_start`.

**Comment by pablomendezroyo** [comment]
Hey! this is critical, can you share the logs from the dappmanager container? available at **packages > system packages > dappmanager > logs**

**Comment by mfw78** [comment]
> Hey! this is critical, can you share the logs from the dappmanager container? available at **packages > system packages > dappmanager > logs**

I definitely agree that this is critical. I dumped out the last 2000 lines of the requested logs, you can see these at:

* dappmanager: https://pastebin.com/srNZW5eX

**Comment by mfw78** [comment]
Furthermore to this, using advice, I executed rollbacks by installing the previous versions of `dappmanager` and `core`. Current system report information:

```raw
Core DAppNode Packages versions

    bind.dnp.dappnode.eth: 0.2.6
    core.dnp.dappnode.eth: 0.2.63
    dappmanager.dnp.dappnode.eth: 0.2.58, commit: b1f45ef6
    https.dnp.dappnode.eth: 0.1.4
    ipfs.dnp.dappnode.eth: 0.2.18
    vpn.dnp.dappnode.eth:
    wifi.dnp.dappnode.eth: 0.2.8
    wireguard.dnp.dappnode.eth: 0.1.2

System info

    dockerComposeVersion: 1.25.5
    dockerServerVersion: 20.10.6
    dockerCliVersion: 20.10.6
    os: debian
    versionCodename: bullseye
    architecture: amd64
    kernel: 5.10.0-13-amd64
    Disk usage: 49%
```

I can confirm that in this configuration, I'm able to install packages with ease and the UI is snappier (as taken by the time to access the 'Stakers' page).

**Comment by xtremal** [comment]
@mfw78 how could you managed to downgrade the dappmanager package? Is there a bash script or something else, because the UI has no such option.

**Comment by mfw78** [comment]
> @mfw78 how could you managed to downgrade the dappmanager package? Is there a bash script or something else, because the UI has no such option.

If you use the explorer (https://dappnode.github.io/explorer/#/), you can find the previous version's IPFS hash. Once you've got this, if you go to the `Dappstore` section on your Dappnode, you can paste in the IPFS hash and click search. It's not intuitive, but this method does allow you to rollback. 

When doing this, you will have to use 'Advanced Options' to allow installation from 'unknown sources'.

Be careful when undertaking arbitrary rollback action. Some packages may have database migrations that don't support rollback. I can confirm this wasn't an issue for me from dappmanager v0.2.59 to v0.2.58.

Hopefully this is a fix coming for this issue in the very near future.

**Comment by xtremal** [comment]
> > @mfw78 how could you managed to downgrade the dappmanager package? Is there a bash script or something else, because the UI has no such option.
> 
> If you use the explorer (https://dappnode.github.io/explorer/#/), you can find the previous version's IPFS hash. Once you've got this, if you go to the `Dappstore` section on your Dappnode, you can paste in the IPFS hash and click search. It's not intuitive, but this method does allow you to rollback.
> 
> When doing this, you will have to use 'Advanced Options' to allow installation from 'unknown sources'.
> 
> Be careful when undertaking arbitrary rollback action. Some packages may have database migrations that don't support rollback. I can confirm this wasn't an issue for me from dappmanager v0.2.59 to v0.2.58.
> 
> Hopefully this is a fix coming for this issue in the very near future.

Thank you! I was able to downgrade the dappmanager package. Unfortunately the cpu is still skyrockets :(

**Comment by pablomendezroyo** [comment]
Are you still having this high CPU consume with the latest dappmanager ?

**Comment by mfw78** [comment]
@pablomendezroyo This issue has been resolved with the release of the most recent dappmanager.

**Comment by pablomendezroyo** [comment]
Great! pls let us know whenever you have a similar issue, sorry for the inconvenience

**Comment by pablomendezroyo** [comment]
Not anymore,

For the future https://github.com/dappnode/DNP_DAPPMANAGER/issues/1335
