### ISSUE TITLE
Implement non-solo staking protocols in the stakers UI

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1369]
Right now the Stakers UI only supports solo Staker (32 Eth). There are many technologies meant to support staking with less Eth using DVT and other approaches.

The Stakers UI must support these new protocols that are meant to be in production by the year 2023.

**Frontend**
- [ ] Implement a launchpad for staking:
   - The launchpad must have the following steps:
      1. Select protocol: solo, obol, rocketpool, stakehouse...
         - ⚠️ Research which protocols require a fixed Fee Recipient and skip step 4 if so:
           - Rocketpool
      3. Select EC
      4. Select CC
      5. Select MEV
      6. Set Fee Recipient
      7. Import keystores + passwords
         - Implement the drag-and-drop section
   - After finishing the launchpad the packages installation + the import (FR and keystores and tag) will be done in the background
   - There must be shown a proper spinner, this process may take a long time (up to 5 packages). The ideal solution to avoid the user getting frustrated would be to have a loading section in the UI for packages been installed: see https://github.com/dappnode/DNP_DAPPMANAGER/issues/1368

- [ ] Implement a button to trigger the launchpad
- [ ] Implement a checker to ensure that the user has visited already the Stakers UI or not to trigger the launchpad. Consider also triggering the launchpad whenever the user has installed the pkgs for the corresponding network
- [ ] Add a new column for protocols / tags in the Stakers UI

**Backend**

- [ ] Implement the backend for the launchpad:
   1. Install the signer first to do the import (keystores + FR + tag) at the beginning. If there is any failure, remove it and do not continue
   2. Continue with the rest of the installation, on failure rollback and uninstall.
   - ⚠️ In any case keystores must be never persisted on dappmanager

**Depends on**
- The process of importing keystores + FR + tag depends on StakingBrain implementation ✅ 

**Refs**
- Protocols to be supported: diva, obol, stakehouse, stakewise, rocketpool, ssv
- Tags: corresponds to the protocol used. Used at the time of importing

**Comment by dsimog01** [comment]
![image](https://user-images.githubusercontent.com/47595345/221624649-566a4ccc-fffb-4dc3-9717-5544279210f3.png)
