### ISSUE TITLE
Move FeeRecipient input from the consensus client to a more "generic" view

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1386]
There will be a global env `FEE_RECIPIENT_<NETWORK>` per network (prater, gnosis mainnet) to define the default global env to be used as solo-staker. See https://github.com/dappnode/DNP_DAPPMANAGER/pull/1380

- [ ] Look for a proper place in the Stakers UI to set this Global env value
- [ ] Add to the backend the globalEnvSet 
- [ ] Add to every consensus client (validator service) pkg the global env `FEE_RECIPIENT_<NETWORK>`. If empty set burn address.

**Comment by dsimog01** [comment]
I would add the fee recipient field in the top right corner of the stakers UI, in the free space on the right of the instructions maybe
![image](https://user-images.githubusercontent.com/47595345/220924592-1db4d6d6-a26d-4117-94e6-56d8842ad36b.png)
