### ISSUE TITLE
Add migration to ensure docker aliases consistency

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1402]
Add a migration to ensure docker compose aliases consistency.
Having a package name `example.dnp.dappnode.eth` the aliases should be:
- `example.dappnode` if the package is mono service
- `service1.example.dappnode`  if the package is multiservice 
- `service1.example.dappnode` and `example.dappnode` if the package is multiservice and has in manifest `mainservice`

**Comment by Marketen** [comment]
As discused today  @pablomendezroyo @dsimog01 , we should change alias rules to:

- For `dnp` packages  ( `example.dnp.dappnode.eth`).  Whether it's a mono or multi-service package:
  - Each service should have an alias format of `<service_name>.example.dappnode`.
  - If it's the main service, also include `example.dappnode`.

- For `public` packages ( `example.public.dappnode.eth`). Whether it's a mono or multi-service package:
  - Each service should have an alias format of `<service_name>.example.public.dappnode`.
  - If it's the main service, also include `example.public.dappnode`.
  
  Is this correct?

**Comment by pablomendezroyo** [comment]
@Marketen thats correct!

**Comment by pablomendezroyo** [comment]
Completed
