### ISSUE TITLE
(Global ENVs) External and internal IP should be provided to all the packages

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#146]
To avoid that the packages have to consult centralized services to obtain the public IP address, we've to find a way to facilitate this ip from the dappmanager

**Comment by dapplion** [comment]
Introduce the concept of global DAppNode variables. The DAPPMANAGER will add a .env file which is common among all packages with at least this variables: 
- EXTERNAL_IP: 85.84.83.82
- INTERNAL_IP: 192.168.1.0
- HOSTNAME: AmazingDAppnode
- DOMAIN: ab34126ab.dyndns.dappnode.eth

**Comment by dapplion** [comment]
Close in favor of https://github.com/dappnode/DAppNode/issues/69
