### ISSUE TITLE
IPFS isn't resolving when it is set as remote

### ISSUE THREAD

**Issue by alexgonmad** [dappnode/DNP_DAPPMANAGER#1470]
IPFS shows error in auto diagnose when it is set to remote
![image](https://user-images.githubusercontent.com/104903362/236433342-a0b6dad1-79ca-4911-b999-0e8273264334.png)

**Comment by dsimog01** [comment]
This is happening to every dappnode that has IPFS remote mode. We should be handling the IPFS repository mode in Support>Auto Diagnose

**Comment by pablomendezroyo** [comment]
It works
