### ISSUE TITLE
Error on host update: Command failed: docker run

### ISSUE THREAD

**Issue by ligi** [dappnode/DNP_DAPPMANAGER#1479]
I tried to do the host update on my dappnode and see this:

```
Error on host update: Command failed: docker run --rm --privileged --pid=host -t alpine:3.8 nsenter -t 1 -m -u -n -i /bin/bash /usr/src/dappnode/DNCORE/scripts/host/host_update.sh
Error: Error on host update: Command failed: docker run --rm --privileged --pid=host -t alpine:3.8 nsenter -t 1 -m -u -n -i /bin/bash /usr/src/dappnode/DNCORE/scripts/host/host_update.sh 

    at /usr/src/app/webpack:/@dappnode/dappmanager/src/utils/shell.ts:35:16
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/index.js:274817:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
Error: Error on host update: Command failed: docker run --rm --privileged --pid=host -t alpine:3.8 nsenter -t 1 -m -u -n -i /bin/bash /usr/src/dappnode/DNCORE/scripts/host/host_update.sh 

    at http://my.dappnode/static/js/main.17fcdcc7.js:2:10025
    at l (http://my.dappnode/static/js/main.17fcdcc7.js:2:541368)
    at Generator._invoke (http://my.dappnode/static/js/main.17fcdcc7.js:2:541156)
    at Generator.next (http://my.dappnode/static/js/main.17fcdcc7.js:2:541797)
    at r (http://my.dappnode/static/js/main.17fcdcc7.js:2:688019)
    at s (http://my.dappnode/static/js/main.17fcdcc7.js:2:688222)
    at http://my.dappnode/static/js/main.17fcdcc7.js:2:688281
    at new Promise (<anonymous>)
    at http://my.dappnode/static/js/main.17fcdcc7.js:2:688162
    at p (http://my.dappnode/static/js/main.17fcdcc7.js:2:9842)
```

![image](https://user-images.githubusercontent.com/111600/159658620-31817830-2f33-49c9-b664-3f898090a714.png)

System info:

_Before filing a new topic, please_ _provide the following information_*.*

## Core DAppNode Packages versions
* **bind.dnp.dappnode.eth**: 0.2.6
* **core.dnp.dappnode.eth**: 0.2.52
* **dappmanager.dnp.dappnode.eth**: 0.2.47, commit: 35c4a081
* **https.dnp.dappnode.eth**: 0.1.3
* **ipfs.dnp.dappnode.eth**: 0.2.15
* **vpn.dnp.dappnode.eth**: 0.2.8, commit: f9a8743e
* **wifi.dnp.dappnode.eth**: 0.2.8
* **wireguard.dnp.dappnode.eth**: 0.1.1

## System info
* **dockerComposeVersion**: 1.25.5
* **dockerServerVersion**: 19.03.8
* **dockerCliVersion**: 19.03.8
* **os**: debian
* **versionCodename**: buster
* **architecture**: amd64
* **kernel**: 4.19.0-9-amd64
* **Disk usage**: 85%

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5459570/buckets/29540291/todos/5380364311) by [Unito](https://www.unito.io)

**Comment by pablomendezroyo** [comment]
Fixed in current core release v0.2.91
