### ISSUE TITLE
Alias my.dappnode erased from the container

### ISSUE THREAD

**Issue by alexgonmad** [dappnode/DNP_DAPPMANAGER#1484]
My Wireguard container (and many others) stopped working beacause it needed the alias "my.dappnode" from the dappmanager container and coudn't resolve it because it got erased.

I had an out of memory (OOM) exception in the container that could be related to this issue.

I managed to fix it by rewriting the docker-compose of dappmanager and adding the alias again.

**Comment by dsimog01** [comment]
The fix needs to be reviewed and re-tested: https://github.com/dappnode/DNP_WIREGUARD/pull/31

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/DNP_WIREGUARD/pull/31
