### ISSUE TITLE
DAppnode/DNP_DAPPMANAGER
#Dappnode
✨ALEX_BITCoin/winner✨ 
@Dappnode



### ISSUE THREAD

**Issue by Alex43ice** [dappnode/DNP_DAPPMANAGER#1488]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**Oin

**Describe alternatives you've considered**

**Additional context**

**Comment by alexpeterson91** [comment]
this is spam. follow the guide for issues.
