### ISSUE TITLE
DOMAIN.dyndns.dappnode.io needs to recreate if the public IP changes (without rebooting)

### ISSUE THREAD

**Issue by mgarciate** [dappnode/DNP_DAPPMANAGER#1499]
**Describe the bug**

The public DOMAIN (DOMAIN.dyndns.dappnode.io) is probably not changing the IP that resolves.

**To Reproduce**

It happens when you reboot your router and changes your public IP and you don't reboot your dappnode.

**Expected behavior**

The public DOMAIN should continue working

**Screenshots**

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by pablomendezroyo** [comment]
It should be updated every 30 minutes

See https://github.com/dappnode/DNP_DAPPMANAGER/blob/develop/packages/daemons/src/dyndns/index.ts
