### ISSUE TITLE
Improve disk usage monitoring

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#152]
Add a second threshold affecting non-core packages:
1. If diskAvailable < 5GB => Stop all non-core DNPs
2. If diskAvailable < 1GB => Stop all non-core DNPs + ETHCHAIN + IPFS

**Comment by dapplion** [comment]
@Shelpin Can you verify that the thresholds work as expected? Thank you! The branch you should test against is :dev

**Comment by Shelpin** [comment]
Thanks!!!!Sure! will install a machine now with the dev branch of dappmanager and let it get full a few  times...!

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_DAPPMANAGER/releases/tag/v0.2.1
