### ISSUE TITLE
Integrate ethical metrics in dappmanager

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1555]
Integrate ethical metrics in the dappmanager so dappnode users can easily trigger it as a core functionality of the dappnode:

- [x] New global envs: `ETHICAL_METRICS_ENABLED` and `ETHICAL_METRICS_EMAIL`
- [x] Add cron similar to ethClientInstaller to ensure that on `ETHICAL_METRICS_ENABLED=true` && `ETHICAL_METRICS_EMAIL!=undefined` the ethical metrics, exporter, and DMS packages are installed and running.
- [x] Add cron to event bus so it can be triggered asyncronously
- [x] Add in **system > notifications** a new input for Ethical metrics that allows the user to switch on and off the notifications system. Also, add a mandatory input for the email.
- [ ] Add to onboarding a view to enable or not ethical metrics on dappmanager initial setup
- [ ] Add initial migration script to set the default values of mail and ethical metrics enabled by checking these packages and its envs

**Comment by Marketen** [comment]
We could make sure that all the functionalities we had in the Ethical Metrics frontend are in the dappmanager integration
- Register/Unregister buttons
- Show instance (could be blurred by default, may be sensitive)
- DMS and Exporter health checks


![Image](https://github.com/dappnode/DNP_DAPPMANAGER/assets/36164126/95a8402f-8286-4e1c-9816-a797d744eb10)
