### ISSUE TITLE
Dappmanager printing "Error: Can't set headers after they are sent" in loop

### ISSUE THREAD

**Issue by Marketen** [dappnode/DNP_DAPPMANAGER#1605]
Context: The error `"Error: Can't set headers after they are sent."` means that you're already in the Body or Finished state, but some function tried to set a header or statusCode

https://dev.to/8thesource/error-errhttpheaderssent-cannot-set-headers-after-they-are-sent-to-the-client-4and#:~:text=The%20error%20%22Error%3A%20Can',body%20has%20already%20been%20written.

**Comment by dappnodedev** [comment]
We have not been able to reproduce this error anymore. It might have been related to some error catching in the monitor proxy that ended up sending it to the dappmanager: https://github.com/dappnode/monitor-proxy/pull/56
