### ISSUE TITLE
Remove bind as `dns` from all running containers

### ISSUE THREAD

**Issue by dappnodedev** [dappnode/DNP_DAPPMANAGER#1649]
After publishing a dappmanager release that includes https://github.com/dappnode/DNP_DAPPMANAGER/pull/1646 , all `docker-compose` files will not include the `dns` setting, but the docker containers created from that compose file might still be using the bind package as dns server, so we need to restart those with the new config.

In theory, executing `docker compose ... up` will only restart those containers whose docker compose file has been edited since they are running

**Comment by pablomendezroyo** [comment]
Completed. If not restarted BIND should forward to docker dns
