### ISSUE TITLE
Improve auto updates delay

### ISSUE THREAD

**Issue by dappnodedev** [dappnode/DNP_DAPPMANAGER#1666]
We should review the auto updates delay taking into account that:

1. We might want to extend the delay up to a week, for example, in order to receive any bug reports as soon as possible so as to reduce the number of users suffering them
2. We might want to increase/decrease delay depending on update criticality
3. We might still want to force an auto update immediately in case that it includes a critical bug fix

**Comment by pablomendezroyo** [comment]
Transfering to https://github.com/dappnode/DNP_DAPPMANAGER/issues/1722
