### ISSUE TITLE
Do a nc to check if all ports are open

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#175]
Some users had trouble opening low ports. Do a network check and alert the user if some ports are not open. Related to https://github.com/dappnode/DNP_VPN/issues/56, use the output of the upnpc module.

https://www.cyberciti.biz/faq/linux-port-scanning/

**Comment by eduadiez** [comment]
Add this check to status report

**Comment by dapplion** [comment]
@vdo Could you investigate how to reliably detect this for both TCP and UDP? Then I will do the implementation on DAppNode

**Comment by vdo** [comment]
As UDP is not connection oriented, it can give false positives depending on the router (check https://en.wikipedia.org/wiki/Port_scanner#UDP_scanning), I would only give this warning trying with TCP ports.

**Comment by pablomendezroyo** [comment]
closed with this issue https://github.com/dappnode/DNP_DAPPMANAGER/issues/601
