### ISSUE TITLE
Gnosis clients support

### ISSUE THREAD

**Issue by 4rgon4ut** [dappnode/DNP_DAPPMANAGER#1803]
### Rationale

We are trying to make client diversity options more accessible for Gnosis validators. In that sense we would like to push Erigon and Nimbus packages for gnosis. As those changes require several PRs to be merged, this issue planed to be used for tracking. The goals is to publish and make Erigon and Nimbus clients for Gnosis chain available on a dappstore.
Coordinated with @pablomendezroyo 

#### Packages updates
 - [x] Gnosis Erigon should be added to StakingBrain to make web3signer support it. Also the new image should be published in registry. 
    https://github.com/dappnode/StakingBrain/pull/279

 - [x] https://github.com/dappnode/DAppNodePackage-Gnosis-Chain-Erigon/pull/40
 - [x] StakingBrain image version should be updated
 https://github.com/dappnode/DAppNodePackage-web3signer-gnosis/pull/78
 - [x] https://github.com/gnosischain/DAppNodePackage-nimbus-gnosis/pull/15

#### Publishing
 - [x] https://github.com/dappnode/DNP_DAPPMANAGER/pull/1820
 - [x] https://github.com/dappnode/DNP_DAPPMANAGER/pull/1834
 - [x] https://github.com/dappnode/DNP_DAPPMANAGER/pull/1835

**Comment by 4rgon4ut** [comment]
@pablomendezroyo Is there are any specific things should be done for this (regarding `wontfix` label)? https://github.com/dappnode/DAppNodePackage-Gnosis-Chain-Erigon/pull/40

**Comment by 4rgon4ut** [comment]
>  - [x] StakingBrain image version should be updated
>  https://github.com/dappnode/DAppNodePackage-web3signer-gnosis/pull/78

@pablomendezroyo Dont I need to update this [parent image](https://github.com/dappnode/DAppNodePackage-web3signer-gnosis/blob/master/brain/Dockerfile#L1) version once StakingBrain PR merged?

**Comment by pablomendezroyo** [comment]
> parent image

True, you should do a PR with the bump of the brain

**Comment by 4rgon4ut** [comment]
According to dappnode naming convention, naming for execution clients packages should follow the format: `network-client` 
Added changes contain names in wrong format: `erigon-gnosis.dnp.dappnode.eth` and thus should be updated to `gnosis-erigon.dnp.dappnode.eth`

PRs:
- [ ] https://github.com/dappnode/DAppNodePackage-Gnosis-Chain-Erigon/pull/49
- [ ] https://github.com/dappnode/StakingBrain/pull/290
- [ ] https://github.com/gnosischain/DAppNodePackage-nimbus-gnosis/pull/26
- [ ] https://github.com/dappnode/DNP_DAPPMANAGER/pull/1834

**Comment by pablomendezroyo** [comment]
Done! 🚀
