### ISSUE TITLE
Implement Smooth in Dappmanager

### ISSUE THREAD

**Issue by Marketen** [dappnode/DNP_DAPPMANAGER#1808]
The main objective of implementing Smooth in Dappmanager is to advertise and make it visible to the users, without being too invasive.

Two main components to add:
- Banner in mainnet/prater stakers tab: Should be a simple banner advertising Smooth to node operators, a link to Smooth Docs or more info should be present.

![Screenshot_20240124_160700](https://github.com/dappnode/DNP_DAPPMANAGER/assets/36164126/3fb56d70-02a0-48bf-aebd-be83b91e28ac)

- Alert (newFeature) when logging for the next time in each dappnode. This should contain more info than banner (link to docs, link to brain, link to UI...)

WIP:
![Screenshot_20240124_161258](https://github.com/dappnode/DNP_DAPPMANAGER/assets/36164126/62de8494-ab4b-4b95-bd1d-60b8ac44a73c)

**Comment by GiselleNessi** [comment]
This issue has been updated

Smooth modal will show if web3signer is installed
Banner will show on the stakers tab

<img width="1463" alt="Screenshot 2024-02-26 at 5 36 22 PM" src="https://github.com/dapp
<img width="1447" alt="Screenshot 2024-02-27 at 1 08 48 PM" src="https://github.com/dappnode/DNP_DAPPMANAGER/assets/53020124/4f438b1e-f0a2-4ca8-a78a-16f9d2f03736">
node/DNP_DAPPMANAGER/assets/53020124/10f5fae5-a591-48de-a65f-465edc98e8a7">
