### ISSUE TITLE
--no-ancient-blocks is removed after restoring the system

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#182]
Just tried to check if when doing a restore with 

```sudo wget -O - https://github.com/dappnode/DAppNode/releases/download/v0.1.18/dappnode_install.sh | sudo UPDATE=true bash```

it maintained the -no-ancient-blocks setting in ethchain and it did not. 

When i run the script and enter the ethchain package the env vars field was empty and the ethchain logs were showing old blocks being synced.

Before filing a new issue, please provide the following information.

Current versions
ethchain.dnp.dappnode.eth: 0.1.14
dappmanager.dnp.dappnode.eth: 0.1.21
ipfs.dnp.dappnode.eth: 0.1.4
vpn.dnp.dappnode.eth: 0.1.21
core.dnp.dappnode.eth: 0.1.19
admin.dnp.dappnode.eth: 0.1.16
bind.dnp.dappnode.eth: 0.1.6
wifi.dnp.dappnode.eth: 0.1.0
ethforward.dnp.dappnode.eth: 0.1.5
wamp.dnp.dappnode.eth: 0.1.1
System info
Disk usage: 82%
Docker version: Docker version 17.05.0-ce, build v17.05.0-ce
Docker compose version: docker-compose version 1.20.1, build 5d8c71b

**Comment by dapplion** [comment]
Closed in favour of https://github.com/dappnode/DAppNode_Installer/issues/49
