### ISSUE TITLE
Rely on docker aliases instead of global envs for clients selection in stakers

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#1844]
The current approach for handling the clients selection in the stakers UI is a monolithic solution that makes it hard to add new clients to any network, adds a lot logic to the entrypoints of the client and forces packages to be restarted to realize about the new client selected among other disadvantages.

A cleaner and more simple solution would be to create a new docker network `staker_network` and use unique docker aliases per network and docker host and hardcode these aliases in the entrypoints of each client, trusting that the dappmanager will take care on setting the correct alias whenever the user selects a client.

There will be a pair of docker aliases per network and they will look something like:

- execution.network.dappnode
- consensus.network.dappnode
- signer.network.dappnode
- mev-boost.network.dappnode

The implementation in the dappmanager will be:

- [ ] Ensure aliases' uniqueness. 
  - **docker does not ensure aliases uniqueness which might result in DNS conflict resolution**. Currently, the docker aliases are:
    - container ID
    - container name `DAppNodePackage-api-ui.ethical-metrics.dnp.dappnode.eth`
    - service name (custom): `api-ui`
    - `serviceName.dnpName.dappnode` (custom): `api-ui.ethical-metrics.dappnode`
  - [ ] Do not allow setting of custom aliases in compose files in the dappnode installer and SDK
  - [ ] ENS ensures already uniqueness so dappmanager installer just need to ensure none packages have other ens as aliases or part of its aliases.
- [ ] docker network `staker_network` settings must be persisted in docker compose files for resilience
- [ ] The staker UI selection will consist of:
  1. Disconnect prev client, stop it and remove settings from compose
  2. Add docker network settings to compose and startup
- [ ] Test if containers need or does not need to be restarted to avoid cache issues whenever the container behind the unique alias changes
- [ ] Keep setting global envs for backwards compatibility
- [ ] Keep the existing `dncore_network` configuration
- [ ] Initial migration for setting the aliases of the clients selected for the first time

The work in the packages will be:

- [ ] Use of fullnode execution in consensus clients, removal of unused global envs and clean entrypoints
- [ ] Use of fullnode consensus in execution clients, removal of unused glglobalonbal envs and clean entrypoints
- [ ] Set `minimumDappnodeVersion` that supports the fullnode aliases implementation
- [ ] Use 1 jwt per network, this will be a breaking change and in orther to make these packages updated at the same time the usage of `optionalDependencies` might be required

**Comment by dappnodedev** [comment]
Currently execution aliases look like: `prater.fullnode.dappnode` so after this implementation it would probably be: `prater.consensus.fullnode.dappnode` or `consensus.prater.fullnode.dappnode`

**Comment by dappnodedev** [comment]
Apart from this I would argue that the best naming could be:
`beacon.prater.dappnode`
`validator.prater.dappnode`
execution.prater.dappnode`

However, we must take into account that nimbus has only 1 service and beacon chain port will be different from the rest

**Comment by dappnodedev** [comment]
For the validator API we must use a Bearer token, and we need to be sure that we can use the same token for every consensus client in each network, so this must be thought and tested

**Comment by pablomendezroyo** [comment]
Release flow would be:

1. Core with Dappmanager implementation: dappmanager will keep injecting global envs and from now will start changing the fullnode alias.
2. Every new client published with fullnode implementation will must have the requirement `minimumDappnodeVersion` set to the fullnode core version.
3. In web3sigenr: keep using global env `CONSENSUS_CLIENT` for service brain so it knows when to use tls for teku validator auth. Consider researching how to get out of this global env too.
4. Publish at the same time execution and consensus clients with fullnode implementation with `optionalDependencies` set. It must be tested if `optionalDependencies` throws an error when the package is installed and cannot be updated to the defined version.

**Comment by dappnodedev** [comment]
@pablomendezroyo suggested in last meeting that we could create a new network called, for example, `stakers-network` to which only the clients selected in the stakers UI would be connected, so that it is impossible that a consensus client outside the network can connect to the execution client. This would allow us to have domains like:
`execution.prater.dappnode`, `beacon.prater.dappnode`, `validator.prater.dappnode` or even `signer.prater.dappnode`

Apart from this, we need to think about how would this affect to DNS resolution made by bind package
