### ISSUE TITLE
Installation stuck at 99%

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_DAPPMANAGER#190]
Sometimes, when installing packages, the download stops at 99% and fails to load the image. 
Starting the installation again seems to solve the issue.

Relevant logs:
```
WARN [modules/ipfs/ipfsTasks] [] : IPFS downloaded file ./dnp_repo/goerli-geth.dnp.dappnode.eth/goerli-geth.dnp.dappnode.eth_0.2.0.tar.xz is invalid: it's size is 0 bytes
INFO [utils/registerHandler] [] : Call requestChainData success: Requested chain data until 1554971764689
WARN [modules/ipfs/ipfsTasks] [] : IPFS downloaded file ./dnp_repo/goerli-geth.dnp.dappnode.eth/goerli-geth.dnp.dappnode.eth_0.2.0.tar.xz is invalid: it's size is 0 bytes
WARN [modules/ipfs/ipfsTasks] [] : IPFS downloaded file ./dnp_repo/goerli-geth.dnp.dappnode.eth/goerli-geth.dnp.dappnode.eth_0.2.0.tar.xz is invalid: it's size is 0 bytes
ERROR [utils/registerHandler] [] : Call installPackage.dappmanager.dnp.dappnode.eth error: Timeout to cancel expired
Stack: Error: Timeout to cancel expired
    at Timeout.setTimeout [as _onTimeout] (/usr/src/app/src/modules/ipfs/ipfsTasks.js:86:16)
    at ontimeout (timers.js:475:11)
    at tryOnTimeout (timers.js:310:5)
```

**Comment by dapplion** [comment]
¯\_(ツ)_/¯ IPFS

**Comment by dapplion** [comment]
I have added a custom log when the streamed bytes are more than the expected amount. Below there is an example screen capture of this situation. We suspect that something wrong happens in the stream, where the `.on("data")` gets called more times than it should and it triggers this situation. I don't know how to know when `"data"` event is legit or not. We will keep an eye on this to hopefully find a solution in the future.

![ezgif com-crop](https://user-images.githubusercontent.com/35266934/56362098-58681080-61e9-11e9-8660-fcae7f0427e2.png)

**Comment by dapplion** [comment]
Released on https://github.com/dappnode/DNP_DAPPMANAGER/releases/tag/v0.2.1
