### ISSUE TITLE
nsupdate map DAppNode's dyndns domain to internal IP

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#206]
Should cover the edge case of this issue https://github.com/dappnode/DNP_ADMIN/issues/249: 

Problem: If a friend is in your house and you want to give her/him VPN credentials, it will not be possible to access the OpenVPN UI if NAT loopback is disabled.

Case 1: If you are connected in DAppNode's WIFI we can point the domain to the internal IP (problem solved)
Case 2: If you are connected to a different WIFI, that is an edge that we will choose not to cover given the solution for case 1.

- [ ] @vdo Try it manually to see if the hack actually works
- [ ] @dapplion Implement it on the DAPPMANAGER to do it automatically when necessary

**Comment by vdo** [comment]
The hack does not work without making changes in the BIND configuration, I'm going to check if it works adding the dappnode.io zone

**Comment by vdo** [comment]
Adding .dyndns.dappnode.io or dappnode.io zone to bind to be a master and resolve the domain internally would block the rest of the domains *.dappnode.io for example, so adding this registry in a dynamic fashion using nsupdate is not possible with bind.

I would suggest using an alternative method like showing an extra link if NAT loopback is not available.
