### ISSUE TITLE
Impossible to remove ethchain volume with Vipnode installed

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#217]
when you try to remove Ethchainn volume having Vipnode installed, it does not get erased saying that the volume is in use. 

this is the error appearing... also the toast says restarting ethchain rather than removing ethchain

![image](https://user-images.githubusercontent.com/21328788/58468617-2ded6980-813e-11e9-9c40-e5f1d032f237.png)

![image](https://user-images.githubusercontent.com/21328788/58468652-4067a300-813e-11e9-9d4d-93029e1aaa78.png)

**Comment by dapplion** [comment]
Will be fixed with https://github.com/dappnode/DNP_DAPPMANAGER/issues/197

**Comment by dapplion** [comment]
Duplicated
