### ISSUE TITLE
Dependency installed even if it's aready present.

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_DAPPMANAGER#218]
When installing a new version of a package with IPFS, and the package is already present, the dependency is installed again, loosing all previous configuration.

For example I installed a new version of LN, and bitcoin was reinstalled but with the default volume setting.

**Comment by Shelpin** [comment]
is there any way I can test this without touching my bitcoin / LN nodes?  thanks!

**Comment by dapplion** [comment]
It's hard to test this issue especially if you don't want to touch your bitcoin / LN nodes. We could skip testing this issue since it only affected IPFS versions.

**Comment by Shelpin** [comment]
ok! thanks!
