### ISSUE TITLE
Bitcoin and Lightning Nodes STAY stopped after an electricity cut

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#230]
Hi!!! just saw that when my dappnode goes out of electricity and it is switched on  again, bitcoin  and LN nodes are stopped and the user  has to restart them manually

**Comment by dapplion** [comment]
LN already has the restart always https://github.com/dappnode/DAppNodePackage-LightningNetwork/blob/afb640d3fe350f906d1cd8f2766ac87143ebfd84/dappnode_package.json#L19 and bitcoin will in the next release
