### ISSUE TITLE
Packages autoupdate fail if the chain is not synced

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DNP_DAPPMANAGER#251]
when trying to force an update in my packages or system packages there are the followong errors: 

System Pacakges: The counter goes back to 4 minutes when it is over annd tries to update wiithout the chain synced.
My Packages: The update remains "in queue" 

In both  cases the user  has no information about what is going on, until the chain syncs, then the updates are correctly performed.... 

![image](https://user-images.githubusercontent.com/21328788/63586947-ffe3be00-c5a2-11e9-9ac5-5b722c00e42d.png)

![telegram-cloud-photo-size-4-5980938476364870138-y](https://user-images.githubusercontent.com/21328788/63586928-ef334800-c5a2-11e9-9a9c-42a6789758b6.jpg)

![image](https://user-images.githubusercontent.com/21328788/63586962-0bcf8000-c5a3-11e9-8e3c-a5d65f23baa8.png)

**Comment by Shelpin** [comment]
Fixed by @dapplion with a warning when the chain is not syncin

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_ADMIN/commit/04fce2c96c25489e4358abe767a26c6c3c696dda
