### ISSUE TITLE
stdout maxBuffer length exceeded when I tried to download all the logs 

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#302]
I can't download all the logs from prysm-validator.public.dappnode.eth since I get this error:
```
RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:348:14)
    at Socket.emit (events.js:189:13)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:261:13)
    at Socket.Readable.push (_stream_readable.js:220:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)

kwargs = {
  "id": "prysm-validator.public.dappnode.eth",
  "options": {
    "timestamps": false
  }
}
```

**Comment by dapplion** [comment]
According to @eduadiez this error does not happen when calling `docker logs` from a shell, so it must be javascript that is not able to handle the massive stdout. 

**Proposal** Stream the docker logs output to a file and then serve that file to the UI.

**Comment by Leibniz137** [comment]
I hit this as well:

![image](https://user-images.githubusercontent.com/2193797/77259229-58fcf880-6c3d-11ea-850a-9caeda8e8aab.png)

**Comment by dapplion** [comment]
To be fixed with https://github.com/dappnode/DNP_DAPPMANAGER/pull/328
