### ISSUE TITLE
Wrong CPU metrics

### ISSUE THREAD

**Issue by vdo** [dappnode/DNP_DAPPMANAGER#362]
Both with Raspberry Pi 4 ARM Cortex CPU and i5 Six Core Processor i5-9500 (3.0GHz) 9MB Cache,
the dashboard reports 100% CPU usage when it should be close to 20%

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_DAPPMANAGER/commit/8a9bff54706ab8b1884cf7af9caf2a71a180c7c2
