### ISSUE TITLE
Include a check for internet connection in the DAppManager

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DNP_DAPPMANAGER#434]
A common user problem is that they might not read the instructions or read them too fast, and they don't start with their DAppNode connected to the router via Ethernet cable. 

The next step is them trying to get VPN credentials but obviously without Internet connection it's never gonna happen. 

A fix for this is a check for internet (`ping google.com`?) and if no internet is detected, a pop-up warning saying 

```
**No internet connection detected!**

Is your DAppNode connected to the router via Ethernet cable? If not, do so now so your DAppNode can have Internet access
```

Help them before they know they need help!

**Comment by olofedlund** [comment]
I’m one of those people that don’t read instructions. This would have saved me so much time.

It was also my expectation that I would be able to connect my dappnode to my WiFi network. So if I had seen this error message I would have been much helped, but I would also have wondered why the WiFi wouldn’t work.

I think this error message could be improved by somehow mentioning the WiFi such that it would have made it clear to me why I couldn’t use the WiFi and that instead functions as a hot spot (on purpose). I don’t know how to phrase this, but I think something to clarify those expectations would have been good.

**Comment by dapplion** [comment]
> I’m one of those people that don’t read instructions. This would have saved me so much time.
> 
> It was also my expectation that I would be able to connect my dappnode to my WiFi network. So if I had seen this error message I would have been much helped, but I would also have wondered why the WiFi wouldn’t work.
> 
> I think this error message could be improved by somehow mentioning the WiFi such that it would have made it clear to me why I couldn’t use the WiFi and that instead functions as a hot spot (on purpose). I don’t know how to phrase this, but I think something to clarify those expectations would have been good.

Thanks for the suggestion! @pablomendezroyo could you turn this into an issue and add it to the UI?

**Comment by dapplion** [comment]
Fixed in current master
