### ISSUE TITLE
IPNS support

### ISSUE THREAD

**Issue by ligi** [dappnode/DNP_DAPPMANAGER#435]
Currently opening an ENS site that leverages IPNS results in this:

![Selection_064](https://user-images.githubusercontent.com/111600/86643754-3f5da200-bfdd-11ea-9f27-2e28be868ca7.png)

also relevant: https://github.com/dappnode/DAppNodePackage-ipfs-pinner/issues/31

**Comment by pablomendezroyo** [comment]
Proxy deprecated for security reasons, see https://github.com/dappnode/DNP_DAPPMANAGER/pull/1731
