### ISSUE TITLE
Allow batch update for DNPs

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#439]
The same way it is done for System DNPs, for regular DNPs

Merging with issue https://github.com/dappnode/DNP_ADMIN/issues/357

> Now you can only know about an update in the installer section and it is difficult to notice as the button is green as the "Get" one.

> Maybe we could change the button colour to orange in the installer section and
add a little icon in the My packages view to packages with an available update.

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/DNP_DAPPMANAGER/issues/519
