### ISSUE TITLE
Allow for DAppNode to use a local static IP instead of the one provided by router's DHCP

### ISSUE THREAD

**Issue by bingen** [dappnode/DNP_DAPPMANAGER#443]
I see the option to enable an external static IP instead of dyndns service, but not for the local network. Is it possible? It would be nice to have that option.

## Core DNPs versions
- **wifi.dnp.dappnode.eth**: 0.2.0
- **admin.dnp.dappnode.eth**: 0.2.3, commit: ec7bf3c1
- **vpn.dnp.dappnode.eth**: 0.2.0, branch: HEAD, commit: 7b017e9e
- **dappmanager.dnp.dappnode.eth**: 0.2.4, commit: a7dea7e4
- **ipfs.dnp.dappnode.eth**: 0.2.2
- **core.dnp.dappnode.eth**: 0.2.5
- **bind.dnp.dappnode.eth**: 0.2.0
- **ethforward.dnp.dappnode.eth**: 0.2.1
- **wamp.dnp.dappnode.eth**: 0.2.0
- **ethchain.dnp.dappnode.eth**: 0.2.1

## System info
- **docker version**: Docker version 18.09.1-ce, build 4c52b901c6cb019f7552cd93055f9688c6538be4
- **docker compose version**: docker-compose version 1.20.1, build 5d8c71b
- **Disk usage**: 22%

**Comment by ARR552** [comment]
Any news on the static ip?? I would like to configure an static ip too.

**Comment by pablomendezroyo** [comment]
@dsimog01 would be possible to have a host script that implements this functionality and can be trifggered from the UI?

**Comment by dsimog01** [comment]
Yes @pablomendezroyo, I believe it should not be difficult to implement

**Comment by pablomendezroyo** [comment]
Implemented!
