### ISSUE TITLE
Percent complete shouldnt exceed 100%

### ISSUE THREAD

**Issue by mrabino1** [dappnode/DNP_DAPPMANAGER#455]
Exceptionally minor UI defect. 
<img width="1707" alt="2020-11-26_18-27-10" src="https://user-images.githubusercontent.com/4902221/100426270-df04f500-3090-11eb-8920-215023c60da6.png">

**Comment by dapplion** [comment]
Thanks for reporting! The computation of image loaded percentage doesn't take into account multi-service packages, so it goes over 100%.

**Comment by mrabino1** [comment]
gotcha.. no worries.. shall we close? or?

**Comment by dapplion** [comment]
> gotcha.. no worries.. shall we close? or?

We will fix it! It's in our backlog already this issue will be the tracker of the solution until merged
