### ISSUE TITLE
Add Eth2 Beaconchain to the Dashboard

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DNP_DAPPMANAGER#464]
Since in a few hours Eth2 will be its own Blockchain, it should be included in the Dashboard.
 
<img width="1068" alt="Screenshot 2020-12-01 at 09 50 04" src="https://user-images.githubusercontent.com/19168735/100717748-c4958900-33ba-11eb-90fc-8417a8a713e4.png">

**Comment by dapplion** [comment]
I'm researching now but seems that Prysm does not follow the "standard" Eth2.0 API so we can get that type of info now.

**Comment by dapplion** [comment]
Raul from Prysm suggested to do

Compute the current clock slot from the genesis time itself. Then, you can use localhost:3500/eth/v1alpha1/beacon/chainhead and use headSlot. Then you can produce X slots synced / Y slot total = 
```
currentHeadSlot / computeSlot(Date.now)
```
