### ISSUE TITLE
Auto Diagnose: Internet test copy and visualization time

### ISSUE THREAD

**Issue by ruvenni** [dappnode/DNP_DAPPMANAGER#467]
When there is no connection the following message is shown:
![image](https://user-images.githubusercontent.com/69941298/100867964-3b09b800-349b-11eb-9e69-c541e08839ef.png)

The red highlighted part is not offering valuable information to users and that makes it very prone to confusing them.

In addition the message is shown for a very little period of time and it vanishes whenever the test is auto launched again and again, not being shown while the test is running. It should be kept in screen while testing connection in the background, but also letting users know that the test is running again and again, or otherwise allow them to launch the test manually.

**Comment by dapplion** [comment]
Don't make the error log all the URLs it has tried, make it cleaner

**Comment by dapplion** [comment]
Bump @tropicar

**Comment by pablomendezroyo** [comment]
Wont implement as for now
