### ISSUE TITLE
Auto Diagnose: UPNP / Ports connectivity check

### ISSUE THREAD

**Issue by ruvenni** [dappnode/DNP_DAPPMANAGER#468]
It turns out that even having the ports opened in my router, the ports connectivity test is not able to notice.
![image](https://user-images.githubusercontent.com/69941298/100872056-832bd900-34a1-11eb-8cf0-21e31bdff642.png)

UPNP is enabled:
![image](https://user-images.githubusercontent.com/69941298/100872332-f33a5f00-34a1-11eb-8e8f-2a1adf5ba885.png)

Checking from an external online test also shows a positive result:

![image](https://user-images.githubusercontent.com/69941298/100872858-bde24100-34a2-11eb-9470-8f6b2173b3b8.png)

**Comment by dapplion** [comment]
Consider adding a link to check-host in the troubleshooting page so users can test if ports are actually open or not

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_DAPPMANAGER/pull/613
