### ISSUE TITLE
Don't start paused packages after updating them

### ISSUE THREAD

**Issue by TripleSpeeder** [dappnode/DNP_DAPPMANAGER#470]
**Steps to reproduce:**
1. Pause a package
1. Install update for paused package

**Observed behaviour:**
- Although the package was in a paused state when the update starte, the package is running after the update

**Expected behaviour:**
- The package should still be paused after the update was installed

**Background:**
I have 2 situations where this is annoying:
- I have stopped the WIFI package as i don't need it and there are already too much active WIFIs in my area. I need to regularly check if the package is still stopped, as it gets restarted after automatic updates
- I have installed Nethermind package, but had to stop running it temporarily due to insufficient RAM. Today an update of Nethermind was released, so I had to manually stop it again.

System info:
```
Core DAppNode Packages versions
dappmanager.dnp.dappnode.eth: 0.2.37, commit: 2b96e582
core.dnp.dappnode.eth: 0.2.41
wifi.dnp.dappnode.eth: 0.2.5
ipfs.dnp.dappnode.eth: 0.2.12
vpn.dnp.dappnode.eth: 0.2.7, commit: 12ae223f
bind.dnp.dappnode.eth: 0.2.6
System info
docker version: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
docker compose version: docker-compose version 1.25.5, build unknown
platform: linux, x64, 4.19.0-6-amd64
Disk usage: 607308375654```

**Comment by dapplion** [comment]
Thanks for reporting! That's definitely a priority will fix soon

**Comment by olofedlund** [comment]
@TripleSpeeder Stop it. Your bug reports make the rest of us feel inadequate!

Just kidding. :)
