### ISSUE TITLE
Allow DNPs to verify that they belong to the specific dAppNode

### ISSUE THREAD

**Issue by lukagulin** [dappnode/DNP_DAPPMANAGER#473]
By exposing signing endpoint on the DAPPMANAGER, other packages within dAppNode could prove that they are part of a specific dAppNode, but private key would be never shared outside DAPPMANAGER. 
Obviously, it has to be secure. That can be achieved by making it accessible only from the internal dAppNode network. Endpoint specification would be very simple.
-  GET with one query parameter named message which contains actual message to be signed. 
- It would return JSON with two fields: signature and address. 

I propose returning both signature and address because virtually always you would need those together and this seems to me elegant solution.

**Comment by dapplion** [comment]
Thanks for writing the proposal! Since the private key pair is compatible with Ethereum I would suggest to prefix all signatures with something DAppNode specific so the signatures can never be re-used for anything else. If you agree what do you think could be this prefix?

**Comment by edisinovcic** [comment]
Hmm, well technically anything like "dappnode" at the start could be used? So we know how to parse that easily?

I don't have any strong opinion on that front...

**Comment by lukagulin** [comment]
That is a good idea. I don't know whether this proof identity schema is used often so I can't judge whether that would be too constraining. i. e. you're asked to sign a message that can't be repeated, but doesn't fit a predetermined pattern.

Maybe that API by default rejects to sign a message that doesn't fit a pattern, but with additional flags you can make API sign it. That way it warns a developer that his package shouldn't sign just anything, but if they have confidence in message they do it anyway. That is obvious security risk if they just ignore it...

Or just make it sign only timestamps that are X amount of time within time request is received.

**Comment by lukagulin** [comment]
When I think about it, for now it would be good enough just to allow this last option, to sign timestamps around current time only. But, in the future, somebody can raise an issue and that can be easily changed.

**Comment by dapplion** [comment]
Sounds good! I would propose to use the prefix
```
\x1dDappnode Signed Message:\n + packageEnsName + \n + data.length + data
```
Where `packageEnsName` is the ENS domain of the package (`geth.dnp.dappnode.eth`). The DAPPMANAGER can figure that out from he incoming IP. That way other package can't ask to sign data that would be valid for other packages. That should be enough to allow to sign arbitrary messages, or is it overkill?

**Comment by lukagulin** [comment]
Maybe some delimiter between `data.length` and `data` but otherwise it seems great.

**Comment by dapplion** [comment]
I've opened a PR for this functionality https://github.com/dappnode/DNP_DAPPMANAGER/pull/480

Do you think it's best to pass the data to sign as a query param or as the request body?

**Comment by edisinovcic** [comment]
> I've opened a PR for this functionality #480
> 
> Do you think it's best to pass the data to sign as a query param or as the request body?

Let's do it in request body.

**Comment by dapplion** [comment]
> > I've opened a PR for this functionality #480
> > Do you think it's best to pass the data to sign as a query param or as the request body?
> 
> Let's do it in request body.

Updated. Now the entire body as text is the data to sign, i.e.
```
curl http://my.dappnode/sign -X POST -H "Content-Type: text/plain" --data "data-to-sign"
```
