### ISSUE TITLE
Fake 'Wifi is disabled' message in UI

### ISSUE THREAD

**Issue by ruvenni** [dappnode/DNP_DAPPMANAGER#483]
Under System > Security I get `wifi is disabled` message but my wifi hotspot is running and I'm currently connected to the ADMIN UI through it 

![image](https://user-images.githubusercontent.com/69941298/101198438-c170f600-3663-11eb-9e78-4bd4a9acfedb.png)

---
Core DAppNode Packages versions

    vpn.dnp.dappnode.eth: 0.2.7, commit: 12ae223f
    dappmanager.dnp.dappnode.eth: 0.2.37, commit: 2b96e582
    core.dnp.dappnode.eth: 0.2.41
    wifi.dnp.dappnode.eth: 0.2.5
    ipfs.dnp.dappnode.eth: 0.2.12
    bind.dnp.dappnode.eth: 0.2.6

System info

    docker version: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
    docker compose version: docker-compose version 1.25.5, build unknown
    platform: linux, x64, 5.9.0-4-amd64
    Disk usage: 148498494259

**Comment by dapplion** [comment]
@eduadiez We have to review how the WIFI being active is detected when possible

**Comment by dapplion** [comment]
Should be fixed with latest release
