### ISSUE TITLE
fileUpload type isn't showing on the config view

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#484]
fileUpload is properly showed when you install the package, but if you want to change later isn't showing on the config view.
<img width="1464" alt="Screenshot 2020-12-05 at 12 16 21" src="https://user-images.githubusercontent.com/20141918/101241166-15c3b680-36f4-11eb-98d6-0be80f313eb7.png">
<img width="1472" alt="Screenshot 2020-12-05 at 12 17 44" src="https://user-images.githubusercontent.com/20141918/101241167-18bea700-36f4-11eb-91d7-d00fc286de53.png">

**Comment by dapplion** [comment]
This is by design since in all cases I could think you don't want to be re-uploading config files required in the installation. If that is necessary we could expose an option in the setup wizard fields such as 
```json
showAfterInstall: true
```

to change that behaviour

**Comment by pablomendezroyo** [comment]
Not an issue
