### ISSUE TITLE
The status of packages with multiservice functionality is confusing

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#485]
If one of the packages of a multiservice is stopped, it seems like all are failing. This is maybe too alarmist since it may be okay for one package to be stopped on certain occasions.

Maybe we should show `Partial 2/4`in yellow or something similar, or if it's an `exit 0` shows it as stopped but ok.

<img width="1704" alt="Screenshot 2020-12-06 at 19 26 35" src="https://user-images.githubusercontent.com/20141918/101288839-fbbfcc00-37f8-11eb-938e-771852361dd0.png">
<img width="1685" alt="Screenshot 2020-12-06 at 19 01 18" src="https://user-images.githubusercontent.com/20141918/101288815-de8afd80-37f8-11eb-849b-7357b849fe39.png">
<img width="1686" alt="Screenshot 2020-12-06 at 19 01 25" src="https://user-images.githubusercontent.com/20141918/101288814-dcc13a00-37f8-11eb-9caf-213f071cd239.png">

**Comment by eduadiez** [comment]
Taking the containers with an `exit 0` as stopped correctly seems very interesting. This allows having containers that can be stopped after the start depending on the configuration without warning the user.

**Comment by dapplion** [comment]
With docker inspect one can get the precise status of a container and figure out if exited cleanly or not
```json
  "State": {
      "Status": "exited",
      "Running": false,
      "Paused": false,
      "Restarting": false,
      "OOMKilled": false,
      "Dead": false,
      "Pid": 0,
      "ExitCode": 0,
      "Error": "",
      "StartedAt": "2020-12-09T21:58:17.832941005Z",
      "FinishedAt": "2020-12-09T22:00:34.344620139Z"
  }
```
However, from the containers endpoint the status is less rich
```json
[
  {
    "State": "running",
    "Status": "Up 3 weeks"
  },
  {
    "State": "exited",
    "Status": "Exited (137) 19 hours ago"
  }
]
```
So the get the status with detail it should call inspect for each package or parse the Status text.

**Comment by dapplion** [comment]
@eduadiez How should we name each of these package statuses?
- Clean exit, code == 0: 
- Not clean exit, code > 0: 
i.e. Stopped, Crashed

**Comment by eduadiez** [comment]
First proposal:
| docker status | name | color |
| - | - | - |  
| created | created | white or light grey |
| restarting | restarting | yellow |
| running | running | green |
| paused | Paused | light green |
| exited 0 |  Stopped | grey |
| exited >0 |  Crashed | red |
| dead |  dead | red |

**Comment by dapplion** [comment]
Couple notes:
- Now that we want to respect the stopped status when updating packages, a stopped package will become created. So created should look the same as stopped
- Restarting is a bad or good state? In dappnode it usually happens on normal ops when doing a restart or when a package crashes in loop. We should make it either grey, green or red, and decide if it's good or bad.
