### ISSUE TITLE
Add a new network and a networking alias

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#498]
Now we're going to have two networks: `dncore_network` and `public_dappnode` for the HTTP Portal, so we need to add the network alias with the ENS name and also the new network to the docker-compose, so the `public_dappnode` network can connect to the package by using the ENS name.

https://docs.docker.com/compose/compose-file/#aliases

We expect to enable this new network when a user enables the HTTPS functionality on the "Network" tab for a specific port package. 

We also need to notify the HTTP Portal of the need to expose the selected package and port.

**Comment by dapplion** [comment]
Implemented with https://github.com/dappnode/DNP_DAPPMANAGER/pull/615
