### ISSUE TITLE
Not report to github

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#507]
**Is your feature request related to a problem? Please describe.**
Currently, the report option in the UI (support > report), redirects the user to a new github issue. Github should be considered for only tecnical stuff. 

**Describe the solution you'd like**
There are more suitable options such as redirect the user to the forum or discord to post the issue.

**Describe alternatives you've considered**

**Additional context**

![Screenshot from 2020-12-15 08-34-05](https://user-images.githubusercontent.com/41727368/102185176-ee69a800-3eb0-11eb-8d02-58fbca50bc9f.png)

Fixes https://github.com/dappnode/DNP_DAPPMANAGER/issues/507

**Comment by pablomendezroyo** [comment]
A suggestion to solve this issue may be to consider the following suggestion https://github.com/dappnode/DAppNode/issues/229

**Comment by ruvenni** [comment]
As in https://github.com/dappnode/DAppNode/issues/229, I think Tier 1/2 support issues should be reported and handled in the forum (where a ticketing system is working in the background). 

Maybe we should keep the current Github report option but show somehow that it only should be used for Tier 3 (tech stuff)
