### ISSUE TITLE
UX Suggestion: "top right menu to the left of the 3d cube" is hard when discussing with users. A better name or graphic would be helpful.

### ISSUE THREAD

**Issue by olofedlund** [dappnode/DNP_DAPPMANAGER#525]
The amorphous blob, unless it actually has a purpose, should maybe be replaced by something that easily be explained such as the "3d cube top right".

Note, the name of the system is used to the left of the blob so it is different for users even if "dappnode" is the most common so that can not easily be used.

Maybe a name: "info", "properties", "?" maybe stylistic, "system", "identity", "system identity".

**Comment by pablomendezroyo** [comment]
Won't implement
