### ISSUE TITLE
Community tab in support section

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#529]
**Is your feature request related to a problem? Please describe.**
Currently there is no much info about our community platforms in the dappmanager UI. As an open source project, community is one of the most important parts of it.

**Describe the solution you'd like**
Would be nice to have another tab in the UI of the dappmanager at navigationBar > Support > **Community**

![Screenshot from 2020-12-23 12-53-09](https://user-images.githubusercontent.com/41727368/102996759-ebf7f580-4523-11eb-88a2-8727de393dc4.png)

This new tab  may contain information related to the active community platforms in DAppNode: **github**, **discord,** **discourse**, such as invitation link to our discord server and brief summary of channels, forum Link and main topics inside of it, Github repos, incentivate users to colaborate, etc

**Describe alternatives you've considered**

**Additional context**

As a suggestion: a react-bootstrap card with navigations components where each component would be a community platform
![Screenshot from 2020-12-23 12-56-13](https://user-images.githubusercontent.com/41727368/102996703-daaee900-4523-11eb-8340-d3d964b074b3.png)

**Comment by dapplion** [comment]
CC @ruvenni @eduadiez @Pol-Lanski

**Comment by ruvenni** [comment]
As I told Pablo before, this is a very good idea :)
Only remember we all agreed time ago that it is always more convenient to use the word Forum instead of Discourse.

**Comment by Pol-Lanski** [comment]
That's a great idea. 
In my view it should be under the "report" tab and should have:
- for support use the [forum](forum)
- or discuss in the [community](discord)
- report a bug [create an issue](github)

**Comment by dapplion** [comment]
@eduadiez

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/752
