### ISSUE TITLE
Integration of https-portal to the DAppNode

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#541]
# DAppNode on https
## Intro
Integrating https-portal to the DAppNode will make enormous changes to UX, but also to the architecture of DAppNode itself. It will allow users to securely connect to their DAppNodes without VPN from anywhere they want. To be able to integrate https-portal to the DAppNode as a core package, changes have to be made primarily on DNP_DAPPMANAGER, but there are some issues perhaps not in its responsibility.
## System wide changes
For additional level of security, DAppNode needs to ship with another docker network, whose only purpose is to isolate containers exposed to the outside world. In other words, container must necessarily be connected to this network to be publicly available.
## DNP_DAPPMANAGER changes
At the frontend side, there has to be way to add and remove forwardings for each individual package/container and way to choose their public subdomain.

When the user chooses to make a package publicly available DAPPMANAGER needs to:
* Connect appropriate container to the public network with some alias
* Make an API call to the https-portal to add forwarding from the chosen subdomain to the alias specified in the previous step.
* Adjust docker-compose of a package to persist connection to the public network even after restart

Choice of an alias is important because it has to be something that mustn't resolve on the private network.

When taking a package from the public, same step are necessary but in reverse.

This is my rough idea of how this should be done. I am open for discussion.

**Comment by dapplion** [comment]
Awesome proposal! Can wait to add it :fire: 

- Could you spec with detail the "API call to the https-portal" including at work port is the API is available and a query example?

**Comment by lukagulin** [comment]
So this is what I am working on: https://github.com/Shard-Labs/https-portal
There should be more details from the https-portal side, but everything is still work in progress so things can be changed.

**Comment by dapplion** [comment]
With https://github.com/dappnode/DNP_DAPPMANAGER/pull/645 https://github.com/dappnode/DNP_DAPPMANAGER/pull/615
The integration is almost done, only remaining
- [ ] Add simple way in the manifest to declare "exposable services"
- [ ] Read, and persist that info in the DAPPMANAGER
