### ISSUE TITLE
Core packages do not add setup-wizard when installed from scratch

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#570]
output of command: `cat /usr/src/dappnode/DNCORE/dappnode_package-ipfs.json`

![Screenshot from 2021-01-18 13-54-16](https://user-images.githubusercontent.com/41727368/104918274-cb8d5080-5994-11eb-9d47-3f89f5923868.png)

**Comment by dapplion** [comment]
To unstuck this release I've uploaded a modified manifest in the IPFS Github release.

Moving forward we should re-think how to distribute releases when installing from scratch

**Comment by dapplion** [comment]
Partially solved with https://github.com/dappnode/DAppNodeSDK/pull/156

**Comment by dapplion** [comment]
We should find a more permanent solution that affects other files
