### ISSUE TITLE
Include a Test Notification button in UI 

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#573]
After setting up the telegram bot notifications in our DAppNode. It would be interesting to have a button to check if the bot sends the notifications. The same way other apps do like Grafana or Pagerduty. The purpose of this addition is making more user-friendly checking the bot is properly configured.

One example of this, we can find it in grafana notification channel: 
![telegram_notification_grafana](https://user-images.githubusercontent.com/59098811/105055511-6fe5c480-5a73-11eb-8faa-69b4f09dbdaa.png)

In my opinion, it would be more correct to use the name "test notification" or something like that to specify the action of the button.

**Comment by dapplion** [comment]
Implemented with https://github.com/dappnode/DNP_DAPPMANAGER/pull/571
