### ISSUE TITLE
v0.2.38 test issues

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#575]
I did an install from scratch test and found the following issues. All are minor and the core functionality works great!

----

- [x] In system/advanced it should fetch and display the current port. Now it's just blank always. Use the same pattern as above "Fetch port" and meanwhile show a "?". Fixed with add914bf610d317ce9b5a648b76e393e99f67053
- [x] Change "No connection" view, it still references Riot, change for Discord. Fixed with df179f07071b4c805d81c0694175f0b2dba88c01
- [x] Remove IP auth for SignUp in the UI. Fixed with f7a750929da58c0a4d4643339987ba356df7d933
- [x] Add getter for Telegram Token and show it in the UI. Fixed with 0a0b3d2fb0d2fe35935d636ed25e585005a4ccdf
- [x] In the UI > Packages don't show the manifest version but the real installed version. Fixed with 2d347c1af47c79ca4940c841917e3e4baf355095
- [x] Admin UI notifications bubble summary state does not support info level. Fixed with 7d50b45f6b9f5faabd9e71d13ede20dd3ffadfa3
- [x] In DappNodeIdentity dropdown menu don't duplicate the external IP and internal IP if they are the same. Fixed with 3056ba77a4f130d8cd384536b44a701d6c48d7cf
- [x] Sort package names in support / report versions list. Fixed with 8f8e4d7d2ab7f167b5ae38254aaf31a39c6efd81
- [x] Disk space full notification, it's sent every time the DAPPMANAGER restarts, it should persist to disk and not resend. Fixed with bec5fe6f33ad51d814f76f5006dab4a1946244a9
- [x] In auto-update notifications add a proper install URL, it's still pending. Fixed with 361cfb569089e2178e58407ebc4484b5e3d629f1
- [x] Auto-updates notification appeared broken in the Admin UI. Tested and happened again. Fixed with 4fe4dbe45d075681edadb28023865e9470683297
- [x] Review admin auth IP distinction and logic in the Admin UI. Fixed with 3d1ed6ecee84b913e81b894f23d2648fc0c62e76

VPN
- [x] Add vpncli command `vpncli print` or `vpncli show` the credentials install of getting the link. Fixed with https://github.com/dappnode/DNP_VPN/pull/189/commits/db053f8c0ddc4db3b7e2fdd449d27058e40fae4c
- [x] Remove IP auth from the VPN. Fixed with https://github.com/dappnode/DNP_VPN/pull/189/commits/e575edd5e3ed619e2a48f5e23fc87c0da1658a13

Awaiting Edu
- [ ] "Change the DAppNode WIFI credentials" banner appears for VPS. The detection of it not working is not correct now

For latter
- [ ] In setup wizard, add better title in container service.  `${dnpName} - ${serviceName}` only if different.
- [ ] In the setup wizard there should be an option to introduce markdown text
- [ ] Review if the VPN could fetch the hostname on each request to not suffer delay when setting the static IP
- [ ] Notifications are not immediately visible in the UI, something breaks.
- [ ] Future find a more friendly UX way to handle tasks that never resolve like:
    - Reboot
    - Exiting DAPPMANAGER, VPN, WIFI. Due to installation, change ENV or restart

**Comment by Pol-Lanski** [comment]
In the setup wizard there should be an option to introduce markdown text
