### ISSUE TITLE
Add smarter titles in Setup Wizard editor

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#580]
In the setup wizard, add better title in container service. `${dnpName} - ${serviceName}` only if it is different.

These titles 
https://github.com/dappnode/DNP_DAPPMANAGER/blob/85e2b4cf9d0f3f321c1b623fe030a0ce8770dc87/packages/admin-ui/src/components/SetupWizard/EditorAdvanced.tsx#L72
https://github.com/dappnode/DNP_DAPPMANAGER/blob/85e2b4cf9d0f3f321c1b623fe030a0ce8770dc87/packages/admin-ui/src/components/SetupWizard/EditorAdvanced.tsx#L77-L79

will render `Dappmanager` `Dappmanager`

**Comment by pablomendezroyo** [comment]
Wont implement
