### ISSUE TITLE
Geth dashboard for light client is always "syncing"

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#585]
**Describe the bug**
If you run a light client and you have geth, the dashboard card for geth will be "syncing" forever.

**To Reproduce**
Run light client, and install geth

**Expected behavior**
Geth dashboard should not show status "syncing" always. Maybe there is needed to contemplate the light client mode to modify this value.

**Screenshots**

![Screenshot from 2021-01-21 22-23-55](https://user-images.githubusercontent.com/41727368/105460356-f4ab2b00-5c8b-11eb-8c0e-01f8b23c7d0f.png)

**Comment by dapplion** [comment]
I've seen this too. It would require more investigation about how Geth light clients compute the `eth_syncing` method return values. Could you register the return of 
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
```
over time (say each 5 minutes) against a Geth light client?
