### ISSUE TITLE
Wrong default TCP port 8090

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#597]
Port 8092 is used to download the VPN file and setup the VPN connection.

In the file `defaultPortsToOpen.ts` is defined the port **8090, should be 8092 instead**:

```
{ protocol: "TCP", portNumber: 8090 }
```

The array `defaultPortsToOpen` is used when `getPortsToOpen()` throws an error when getting the ports to open.

**Comment by dapplion** [comment]
Part of https://github.com/dappnode/DNP_DAPPMANAGER/issues/598
