### ISSUE TITLE
Enhance port managment features

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#60]
Ports to consider:
- 4001:4001
- 4002:4002/udp
- 8080
- 5001

The two first ports should open by default (4001, 4002).  The other two wouldn't but they could be openable from the ADMINUI.

Next step is letting the user should which ports can be exposed outside, 8181:8080 for example.

**Comment by Shelpin** [comment]
i guess this can be closed with the new port forwarding feature, right??
