### ISSUE TITLE
Add webpage port checking

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#601]
Add this [webpage](https://check-host.net/check-tcp) somewhere in the UI to help users debugging their ports 8092 and 1194 (needed for the VPN connectivity)

I suggest to provide this webpage **only if** there is an error with their ports to not overload the UI. It would be added in **Support > Auto diagnose** if the check **No ports have to be opened OR the router has UPnP enabled** fails
![Screenshot from 2021-01-25 19-25-54](https://user-images.githubusercontent.com/41727368/105749708-146c7880-5f44-11eb-8ae0-50f3bba2ad1f.png)

To provide a better UIx, the hyperlink can be constructed with the parameter of the dappnode DNS like so:

```
https://check-host.net/check-tcp**?host=<DAppNode ID>.dyndns.dappnode.io:8092**
```

**Comment by dapplion** [comment]
Fixed with https://github.com/dappnode/DNP_DAPPMANAGER/pull/613
