### ISSUE TITLE
Report system Info: docker version from dappmanager container instead of from HOST

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#603]
The reports created in the UI have:
- Core DAppNode Packages versions
- System info

In system Info there is gathered the following information
- docker version
- docker compose version
- platform:
- disk usage

**Error:**

Currently at script `diagnose.ts` it is gathered the docker and docker-compose versions from the dappmanager container.

Commands `docker -v` and `docker-compose -v` should be executed against the shell host

I have verified myself that in my dappnode there is shown in the UI my docker versions as:
- docker version: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- docker compose version: docker-compose version 1.25.5, build unknown

This versions match with the container docker versions. Whereas in the host machine the `docker -v` throws a different version

**Comment by dapplion** [comment]
@eduadiez Just realized that it could be possible to have a different docker version in the host and in the DAPPMANAGER. It is technically possible to have incompatibilities if we ever do a major update, just something to keep in mind

**Comment by eduadiez** [comment]
yes, this's something that we should take into account

**Comment by dapplion** [comment]
Closing for https://github.com/dappnode/DNP_DAPPMANAGER/issues/629
