### ISSUE TITLE
Include on the UI an option to store metrics for a customized time by Prometheus

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#607]
In the DMSPackage, there is a container with the service Prometheus, this service is executed with the followings options:
`/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/usr/share/prometheus/console_libraries --web.console.templates=/usr/share/prometheus/consoles`

By default, the metrics are stored for ~15d. But there is an option to change that parameter `--storage.tsdb.retention.time`. It would be interesting to add an easy way to change this flag from the UI and analyze how it can affect, how much space disk requires as long as increment the period the time.

One example of how this parameter works would be:
`--storage.tsdb.retention.time=40d`

The solution could be adding a wizard for the Prometheus Service.

**Comment by dapplion** [comment]
I think adding a setup wizard for the DMS package is the easiest option
