### ISSUE TITLE
Investigate safe parameters for the IPFS concurrency

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#61]
On some cases the IPFS node can return errors if overflowed with requests. To solve this issue a concurrency tasks queue has been implemented to handle the IPFS tasks. However, would be an optimal concurrency value? Setup some tests and investigate.

**Comment by sponnet** [comment]
https://github.com/sponnet/peepin/blob/master/src/ThrottledIPFS.js could be an inspiration for this.

**Comment by Shelpin** [comment]
Not happenend again!! it depends on the hardware. closing

**Comment by sponnet** [comment]
Parameters Are Safu. 😆
