### ISSUE TITLE
Add alias to every container

### ISSUE THREAD

**Issue by lukagulin** [dappnode/DNP_DAPPMANAGER#625]
When connecting containers to the internal `dncore_network`, option `--alias` should be passed so Docker's internal DNS can resolve them properly. This way, updating BIND will be unnecessary and system should be more resilient.

**Comment by dapplion** [comment]
Implemented on https://github.com/dappnode/DNP_DAPPMANAGER/commit/c2cf80f3ff5759998956edec4f3ee2af10b96880
