### ISSUE TITLE
Update docker via host script

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#628]
### Update docker host version using script

Since docker is one of the main technologies of DAppNode would be a useful tool to allow users to update docker from the UI. 

Docker update must be done using **package method** in order to install a specific version and not the latest one. Also because is not able to update docker in debian bullyese via repository.

##### Update: docker or compose

There will be possible to update docker and/or docker compose. For both possibilities there will be mandatory

##### Before updating docker

Before updating docker there will be displayed in the UI the docker/docker-compose version and compare this version to others versions that have been already tested and upgraded.

- There will be stored as metadata in the dappmanager docker versions that have been tested its upgrades to the stable version
- There will be displayed the docker host version before update docker. To achive this it is necessary to execute a host script (the same one but with a specific flag), and return the docker version.
- There will be compare the docker version to the docker versions stored in the dappmanager and give a warming if the docker update is not "supported" by dappnode
- Before update docker will be given a warming saying that the dappnode might be rebooted due to the docker installation

##### Requirements

There will be necessary to full fill some requirements to be able to update docker:

- Debian operating system
- Stretch, buster or bullyese
- Architecture supported by docker (arm64, amd64)
- Current docker version must be less than the stable one. Not allow downgrades

##### Concerns

There might be some cases where the script will execute a reboot:

- When after updating docker, the docker-CLI and docker-server versions are not equal (must be equal). Usually solved rebooting.
- When after updating docker, containers are stopped. There will be tracked the dappmanager container state.
- If containers are in state exited after docker update, and the reboot is done, the wifi container will keep its state exited due to its restart policy

**Comment by pablomendezroyo** [comment]
Would be interesting to have https://docs.docker.com/config/containers/live-restore/ to keep docker containers running during daemon crashes, planned outages, or upgrades.

The flow to add this new feature would be:
1. Create docker json config file: /etc/docker/daemon.json
2. Restart docker daemon: `systemctl reload docker`

##### Concerns
1. This config file could be added in the installer so new dappnodes will have it. The problem would be the current users. The config file could be added in the **update_docker.sh** script (when users attemps to update docker/docker compose).
2. The json file needs a reboot of the docker daemon. This necessity suits perfectly with the **update_docker.sh** script since the script might reboot the system in a few cases.

**Comment by dapplion** [comment]
The live-restore feature is really cool tho we may want to add it only for ISO installations to not manipulate the host without warning. Let's open a new issue for it to consider latter

**Comment by pablomendezroyo** [comment]
Not suitable for DAppNode. 
"Live restore allows you to keep containers running across Docker daemon updates, but is only supported when installing patch releases (YY.MM.x), not for major (YY.MM) daemon upgrades."
