### ISSUE TITLE
Script to collect host details

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#629]
Currently, the only way for dappmanager to get info from the host is to execute a new container that executes a script stored in the host. This might be considered a waste of time and hardware resources.

Information from the host that might be considered useful for the dappmanager:

- Operating system: debian, ubuntu ...
- Architecture: amd64, arm64...
- OS version: buster, stretch, etc
- Tools versions: docker, compose, etc
- Any other stuff required by the dappmanager

To avoid executing scripts that retrieves information from the host every single time that information is needed, would be useful to have a script that retrieves all of this information and returns it to the dappmanager and the dappmanager handles with it to make it persistant.

#### Concerns

- This information might get unupdated after a while, when to execute this script to update this info ?
- Allow users to execute this script from the UI ?

**Comment by dapplion** [comment]
I would run it once per DAPPMANAGER run and cache the result until the DAPPMANAGER process restarts

**Comment by pablomendezroyo** [comment]
closes https://github.com/dappnode/DNP_DAPPMANAGER/pull/650
