### ISSUE TITLE
Add refresh HTTPS mapping button to the UI

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#657]
One of the failure points for HTTPS portal is when containers get restarted and somehow they don't reconnect to the external network. In that situation DAPPMANAGER doesn't show that anything is wrong but forwarding doesn't work and HTTPS portal shows Bad Gateway.
Easy solution for that is to remove and add same mapping. However, even more easier would be if we had a button which you could click and those steps are done automatically. In perfect world that button should be never clicked, but it would improve UX in those circumstances.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/770
