### ISSUE TITLE
Add mDNS for local network discovery

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#669]
**Is your feature request related to a problem? Please describe.**

Right now access to DAppNode and especially during first install is bit cumbersome and it could use some improvements

**Describe the solution you'd like**

Since DAppManager is already mounted to DBus and every linux machine has avahi daemon preinstalled, it would be usefull if DAPPMANAGER could advertise it's local IP adddres on the local network.

Additions that would need to be made to package: 

- Installation of avahi-tools package in the Docker image
- Handling of the `avahi-publish` shell command

**Additional context**

`avahi-publish`shell command is used in a form `avahi-publish -a -R $MDNS_DOMAIN $IP` where `-R` argument is neccesary only if you want to publish more domains pointing to the same IP. It runs in the foreground until it is sent SIGINT (ctrl+c) and during that time all machines on broadcast domain should be able to resolve that domain to the IP

To make this work simple HTTP proxy is also necessary but you can see early version of it [here](https://github.com/Shard-Labs/DAappNode-http-proxy).

```
MDNS_DOMAIN=my.dappnode.local
```

```
IP= fetch dynamicallly
```

**Comment by pablomendezroyo** [comment]
Does it take any security vulnerability to have a daemon that exposes the port continuously running? should be an option to stop such daemon somewhere in the UI or even needed to be explicitly executed from the UI by the user?

**Comment by dapplion** [comment]
> Does it take any security vulnerability to have a daemon that exposes the port continuously running? should be an option to stop such daemon somewhere in the UI or even needed to be explicitly executed from the UI by the user?

This doesn't expose anything new. It just allows participants of the local network to reach the DAppNode at a `.local` IP, instead of having to find and use the DAppNode's host internal IP. The only security consideration would be a phishing attack from another participant of the local network claiming to also be the DAppNode.

**Comment by 3alpha** [comment]
What happens if DAppNode doesn't have internalIP?

**Comment by dapplion** [comment]
> What happens if DAppNode doesn't have internalIP?

Good question I have not tested that scenario, could you if possible?
