### ISSUE TITLE
Limit a container’s access to memory

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#674]
"It is important not to allow a running container to consume too much of the host machine’s memory. On Linux hosts, if the kernel detects that there is not enough memory to perform important system functions, it throws an OOME, or Out Of Memory Exception, and starts killing processes to free up memory. Any process is subject to killing, including Docker and other important applications. This can effectively bring the entire system down if the wrong process is killed."

Info available: https://docs.docker.com/config/containers/resource_constraints/#understand-the-risks-of-running-out-of-memory

Due to the naturality of DAppNode and its DAppNode packages (use to consume a lot of memory), it is a potential use case that can happen. A few users already have experimented and reported this issue.

**Approach***
- [ ] Identify dappnode packages with high memory consumption rates
- [ ] Identify an optimal maximum RAM value to be used by docker containers
- [ ] Determine a way to add this value (e.g [add it to the compose file](https://docs.docker.com/compose/compose-file/compose-file-v3/#resources) )

**Comment by pablomendezroyo** [comment]
This is an interesting feature that docker provides. 

The problem comes with blockchain apps, it is hard to know how much memory should use a node. We cannot determine this value

**Comment by pablomendezroyo** [comment]
There have been already reported two dappnode packages consuming too many host resources:
- Teku
- Nethermind

The result was docker not working as expected. It was required to restart docker daemon.

This is not an issue on DAppNode side but on the upstream project, DAppNode cannot ensure the upstream project will not consume to many resources so it must limit container access to host resources.

**Comment by 3alpha** [comment]
Would this limit crash packages with OOM exception? And is it acceptable if it does?

**Comment by 3alpha** [comment]
Is this done @pablomendezroyo @tropicar ?
