### ISSUE TITLE
Give more visibility to WIFI against VPN

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#698]
**VPN** is one of the most visible items in the dappnode dashboard, whereas it is one of the most advanced (compared to the WIFI)
![image](https://user-images.githubusercontent.com/41727368/113673463-512dbc00-96b9-11eb-83d8-d1d3e449c83e.png)

**WIFI**, on the other hand, is a really hidden feature. It is located at **packages > system packages > wifi**

### Proposal
Give more visibility in the UI to WIFI and consider to relocate the VPN in the UI to a less visible location
More arguments on this issue https://github.com/dappnode/DAppNode/issues/242#event-4554883687

UPDATE:
- Remove SDK
- Add wifi tab above VPN 
- Add docs for both of them and explain when to use each one

**Comment by dapplion** [comment]
Sounds good!

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/742
