### ISSUE TITLE
Set up an remote IPFS endpoint does not work correctly

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#703]
**Describe the bug**
When you set up a remote IPFS endpoint the dappstore does not work. Many errors appear on the logs of the dappmanager like the following :

```
ERROR [calls/fetchDirectory:65] Error fetching ipfs-pinner.dnp.dappnode.eth release Error: Error downloading ipfs-pinner.dnp.dappnode.eth release from IPFS: IPFS hash not available/ipfs/QmTYdV9puiJ3oLwC3W6GGVfGQX3qfcrGZCVcvb21wRPyHP: <!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
Cannot POST /ipfs.dappnode.io/cat
</body>
</html>
    at Object.handleIpfsError (/usr/src/app/webpack:/src/modules/ipfs/utils.ts:8:11)
    at Ipfs.<anonymous> (/usr/src/app/webpack:/src/modules/ipfs/Ipfs.ts:38:7)
    at Generator.throw (<anonymous>)
    at rejected (/usr/src/app/index.js:203062:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**To Reproduce**

1. On the DAppNode UI, go to Packages > System Packages > DAppmanager > Config 
2. Update the env var **IPFS_HOST**, with the value: `ipfs.dappnode.io` or ` https://ipfs.infura.io/` .
3. Restart the dappmanager package.
4. Check if the dappstore show up the packages and if it does not happens, check the logs. 

**Expected behaviour**

The dappstore load and show the packages.

**Comment by dapplion** [comment]
Reviewed IPFS module, and now it uses the minimum number of routes possible. Re-open if it still doesn't work with external providers
