### ISSUE TITLE
Fix aliases for multicontainer packages

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#704]
In current (BIND) name resolution schema, multicontainer packages can specify default container which can be resolved with `<package>.dappnode` and all other containers are resolved with `<container>.<package>.dappnode`, including the default one.

To preserve that functionality in the new schema without BIND, additional alias `<package>.dappnode` must be added via DAPPMANAGER to the default container.

**Comment by dapplion** [comment]
Thanks for reporting! Really good find
