### ISSUE TITLE
Re-enable netlify builds on PR

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#730]
We disabled Netlify builds because it exceeded out max quota. Research how to re-enable and coordinate with @eduadiez to do it:
- Consider creating a separate netlify account just for test builds of the admin UI
- If necessary purchase a higher tier with enough builds / week

Give priority to this issue since it's incredibly helpful for development and I spent significant time setting this up initially

**Comment by pablomendezroyo** [comment]
### Netlify 
- [ ] Choose a pricing plan
- [ ] Create a team and invite dappnode members
- [ ] Give them permissions

### Docs
- Pricing: https://www.netlify.com/pricing/?_ga=2.233627230.1992060333.1618320782-910863074.1612337433#features
- Use of `netlify.toml` vs introduce settings in UI: https://docs.netlify.com/configure-builds/file-based-configuration/

### Use
- There should be deployed a site on every PR against v0.something branches
- There should be deployed a site on every PR against master branch

**Comment by dapplion** [comment]
@pablomendezroyo Current strategy of commenting on commit is extremely verbose. Could it comment once per PR?

**Comment by pablomendezroyo** [comment]
cloed https://github.com/dappnode/DNP_DAPPMANAGER/pull/735
