### ISSUE TITLE
Add the version of the dappmanager on the UI

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#737]
I think it can be interesting to add the version of the dappmanager in some place of the UI. Not only on the system tab.

**Describe the solution you'd like**

This place could be fine.
![example](https://user-images.githubusercontent.com/59098811/114854539-36f48c00-9de5-11eb-8efa-dfa484fd36fc.png)

**Comment by pablomendezroyo** [comment]
I think thats a great idea! but instead of dappmanager version I would put core version (e.0.2.44)

**Comment by pablomendezroyo** [comment]
I still think this would be a little effort issue that may produce a lot of benefit: users would be able to know the core version on a sight shot

**Comment by pablomendezroyo** [comment]
@GiselleNessi @mateumiralles We should discuss this

**Comment by pablomendezroyo** [comment]
Conclusion: add dappnode core version to the bottom left corner

![Uploading Screenshot 2024-03-04 at 16.47.58.png…]()
