### ISSUE TITLE
manual update link on the system tab

### ISSUE THREAD

**Issue by thekit** [dappnode/DNP_DAPPMANAGER#738]
problem: i find that even with autoupdates turned on sometimes i find a day later that core is not updated. also sometimes it is good to manually trigger an update before autoupdate kicks in 24 hours later to see if my test dappnode is happy before i let the update go to the staking machine

desired solution:

a tab in the system menu for manual update, to be inserted between the “auto updates” and “reports” tab that links to the following url

https://my.dappnode/#/system/update

**Describe alternatives you've considered**

workarounds: when core is ready to update the notification bell gives me a notification banner that links to the link  https://my.dappnode/#/system/update

notifications get cleared frequently so i bookmarked that link as of today. it would be much better to have the link permanently in the systems menu.

also i asked the discord and the core team give me links to the ipfs hash but that sometimes comes back with an unverified package error

**Additional context**

no additinal data

**Comment by dapplion** [comment]
I'll like the proposal! @pablomendezroyo and I will take a look into the best approach to add it.

**Comment by pablomendezroyo** [comment]
Manual updates are available now in the UI DASHBOARD

![image](https://user-images.githubusercontent.com/41727368/118244372-c00fe900-b49f-11eb-88c2-6597aec5ab21.png)
