### ISSUE TITLE
DappStore / DappManager indefinitely propagating the packages

### ISSUE THREAD

**Issue by nazariyv** [dappnode/DNP_DAPPMANAGER#746]
**Describe the bug**

Dappmanager does not fetch any packages, logs say ipfs hash is not available. Which is not true.

**To Reproduce**

## Core DAppNode Packages versions
- **bind.dnp.dappnode.eth**: 0.2.6
- **core.dnp.dappnode.eth**: 0.2.42
- **dappmanager.dnp.dappnode.eth**: 0.2.38, commit: 85e2b4cf
- **ipfs.dnp.dappnode.eth**: 0.2.14
- **vpn.dnp.dappnode.eth**: 
- **wifi.dnp.dappnode.eth**: 0.2.6

## System info
- **docker version**: Docker version 18.09.8-ce, build 0dd43dd87fd530113bf44c9bba9ad8b20ce4637f
- **docker compose version**: docker-compose version 1.25.5, build unknown
- **platform**: linux, x64, 5.9.0-4-amd64
- **Disk usage**: 48%

And then go to DappManager

## Issue

None of the packages show. They are all propagating. But when I look at the logs in dappmanager it errors out by saying the ipfs hash is not available for **all** of them. Please advise.

I have tried the solution where I removed the ipfs volumes, which made things worse, since now I can't see any packages. Whereas, before there were some.

Thank you

**Expected behavior**

I can see the packages.

**Screenshots**

![ss11](https://user-images.githubusercontent.com/13678461/115971884-04fccb80-a543-11eb-8c18-8e9a1327e2d4.PNG)

![ss1122](https://user-images.githubusercontent.com/13678461/115971882-04643500-a543-11eb-9ade-d0d52481e7ab.PNG)

**DAppNode version:**

see above

- OS: Your factory Dappnode Xtreme
- Browser: Chrome

**Additional context**

Posted a question in Discord on the 22nd of April: https://discord.com/channels/747647430450741309/747816600077598730/834913650983960596

And did not post this on your forum because it does not allow me to, since it thinks I have links in there, which I don't...

**Comment by nazariyv** [comment]
my setup was cable modem then router and then dappnode xtreme. I have now re-enabled router mode on the modem, so now I have dappnode xtreme connecting directly to the original router. And getting new kinds of errors now

**the last one**

```
ERROR [calls/fetchDirectory:65] Error fetching lightning-network.dnp.dappnode.eth release Error: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Ipfs hash not available: QmcUTeDzb7CoKLNKcz6xynNFzaggC29dfxZzWAsY1vXdip
    at objectSize_1.default.catch.e (/usr/src/app/webpack:/src/modules/ipfs/index.ts:26:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR [calls/fetchDirectory:65] Error fetching lightning-network.dnp.dappnode.eth release Error: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Ipfs hash not available: QmcUTeDzb7CoKLNKcz6xynNFzaggC29dfxZzWAsY1vXdip
    at objectSize_1.default.catch.e (/usr/src/app/webpack:/src/modules/ipfs/index.ts:26:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR [calls/fetchDirectory:65] Error fetching lightning-network.dnp.dappnode.eth release Error: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Error downloading lightning-network.dnp.dappnode.eth release from IPFS: Ipfs hash not available: QmcUTeDzb7CoKLNKcz6xynNFzaggC29dfxZzWAsY1vXdip
    at objectSize_1.default.catch.e (/usr/src/app/webpack:/src/modules/ipfs/index.ts:26:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR [api/logger:34] RPC error fetchCoreUpdateData Error: Error downloading core.dnp.dappnode.eth release from IPFS: Error downloading core.dnp.dappnode.eth release from IPFS: Ipfs hash not available: QmQQJLZYbYtRsorUF9qkLPoX2DEHsTLQVkJrZUHgai9Gqy
    at objectSize_1.default.catch.e (/usr/src/app/webpack:/src/modules/ipfs/index.ts:26:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ERROR [api/logger:34] RPC error fetchCoreUpdateData Error: Error downloading core.dnp.dappnode.eth release from IPFS: Error downloading core.dnp.dappnode.eth release from IPFS: Ipfs hash not available: QmQQJLZYbYtRsorUF9qkLPoX2DEHsTLQVkJrZUHgai9Gqy
    at objectSize_1.default.catch.e (/usr/src/app/webpack:/src/modules/ipfs/index.ts:26:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
WARN  [modules/dappGet/aggregate/aggregateDependencies:66] Error fetching core.dnp.dappnode.eth@0.2.44 dependencies (assuming it has none) { TimeoutError: Request timed out
    at Timeout.setTimeout (/usr/src/app/webpack:/app/node_modules/ipfs-utils/src/http.js:42:1)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10) name: 'TimeoutError' }
```

**Comment by nazariyv** [comment]
I have attempted to reinstall dappnode with the USB that came with the node to no avail. Flashed a new image, and nuked the old dappnode. I have yet to see if this fixed the issue. Closing this for now.

**Comment by dapplion** [comment]
Glad to know you could fix the issue!
