### ISSUE TITLE
Contribution input in the UI

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#749]
Since DAppNode is an open-source project, would be great to add a form of contributions from the UI.

Ideas:
- Somewhere in the UI to redirect to the current gitcoin grants for dappnode
- Smart contract deployed to contribute in dappnode. Make the corresponding logic to add the possibility to contribute directly from the dappnode UI (e.g by calling a SC function)

**Comment by dapplion** [comment]
I would add a link to Gitcoin grants since it's waay more user friendly than anything custom we could do calling a SC directly. They have integrated with an L2 solution which allows to donate much cheaply and their donations get multiplied

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/752
