### ISSUE TITLE
Firmware Update UI

### ISSUE THREAD

**Issue by CMTRACE** [dappnode/DNP_DAPPMANAGER#758]
Goal:
Expose firmware information about the hardware dappnode is running on. Help inform users and guide them to keeping firmware up to date
- Manufacturer
- Model
- Firmware version
- Firmware install date
- Optional firmware version for raid and other platform features
- System and package reliability history
- System events and errors collected and displayed to help track any negative system impacts from firmware updates.

Stretch goal:
Expose and *notify* the user of outdated firmware for the NUC it’s running on.
- Security suggestions similar to those for changing the default WiFi password

Utopia:
Expose, notify and *perform* updates to firmware, initiated by the user

I imagine the best place for this would be under System somewhere but where exactly isn’t super important the team already do a great job with the UI so whatever you think is best. 

Why:
- It’s good practice to keep firmware up to date.
- Tends to help thermal and stability issues.
- Exposing this information will position the dappnode well for the upcoming spectre v2 vulnerabilities once Intel releases a patch.

Risks:
Obviously issues around a poorly tested firmware update can be severe
New issues introduced that negatively impact performance or reliability over time

Mitigation:
- User initiated
- System reliability tracking over time, crash count/ suspected reason
- System events shown in the UI
- Previous version rollback if OEM support is there

**Comment by pablomendezroyo** [comment]
This issue could be splitted into:
- Install missing firmware: https://github.com/dappnode/DNP_DAPPMANAGER/issues/763
- Security updates: https://github.com/dappnode/DNP_DAPPMANAGER/pull/748
