### ISSUE TITLE
.local UI controller

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#761]
Add view in settings to control Avahi daemon:
- Start
- Stop
- View logs
- Un-expose the port 80 from local network

**Comment by pablomendezroyo** [comment]
Related to the name, what about: LND ("Local Network Discovery")?

**Comment by dapplion** [comment]
> Related to the name, what about: LND ("Local Network Discovery")?

Yeah! That's sounds gread

**Comment by dapplion** [comment]
Implemented with https://github.com/dappnode/DNP_DAPPMANAGER/pull/783
