### ISSUE TITLE
Encrypted Backups to a remote location

### ISSUE THREAD

**Issue by mygrexit** [dappnode/DNP_DAPPMANAGER#773]
**Is your feature request related to a problem? Please describe.**

I think it would make sense to perform regular backups in order to be back online with all your packages and nodes quickly in case of a failure or defect. Unfortunately, creating backups is something that is easily forgotten. 

**Describe the solution you'd like**

The ability to upload an encrypted backup to an external server. 
Practical here would be a backup to e.g. S3 or similar services. For Docker backups I use restic or resticker so far. Maybe this can be implemented as an app?

It should be possible to set how often you want to make backups and at what time this should happen.

Resticker already brings all these options, maybe that would be a possibility to implement.

**Describe alternatives you've considered**

The alternative would be to upload manually, but this does not solve the problem of forgetting.

**Comment by pablomendezroyo** [comment]
@mygrexit I think that's a great idea!

### My thoughts 

**What to backup?**
- DAppNode packages data
- ?

**How?**
- What @mygrexit proposed
- Use of any other dappnode package to store such backups?

**cons**
- It might require too much development. Should be a simple and easy solution

@dapplion What do you think?

**Comment by dapplion** [comment]
Yeah this should be doable. restic is really nice. We would have to research how to best integrate that with the current backup definitions and patterns of DAppNode.

**Comment by pablomendezroyo** [comment]
Should we consider adding this for the next release? 

I would say that backups are something requested and appreciated by a lot of dappnode users (specially stakers). The possibility of do automatic backups would be great

**Comment by pablomendezroyo** [comment]
Discussion summary: There are not enough strong reasons to implement this feature, why?
- Most of demmand comes from staking dapps. In these dapps do not make sense to backup neither blockchain data and the state. The password should be something exclusively the user handles

This issue could be reactivated if any dapp consume by the user needs to backup data in a remote location

**Comment by pablomendezroyo** [comment]
wont implement
