### ISSUE TITLE
Add new UI element for HTTPS 

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#774]
HTTPS package will have LOCAL_PROXYING environment variable that controls whether HTTPS acts as a (http) proxy on local network when using mDNS to discover local DAppNode. It will be convenient to users choosing to disable this feature to have nice UI and UX with that.

**Comment by dapplion** [comment]
Implemented with https://github.com/dappnode/DNP_DAPPMANAGER/pull/783
