### ISSUE TITLE
Add configuration with local ip to the Wireugard interface

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#775]
After https://github.com/dappnode/DNP_WIREGUARD/issues/9 is implemented it would be useful to have some way to fetch that configuraiton directly from DAPPMANAGER/s UI for users with NAT loopback issues.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/777
