### ISSUE TITLE
Change graffiti on the prysm package causes visual bug on the dashboard

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#779]
**Describe the bug**

If you have installed prism package or Pyrmont package, and you change the graffiti, not the dashboard appear a red light and indicate the package is `DAppNode Package stopped or unreachable (connection refused)` The error does not remove after restarting the package, even restarting the box. I don't know if this error is related to the package itself or something related to the Dappmanager.

**To Reproduce**

**Expected behaviour**

This error should not appear. It's visual, the package works correctly. You can access the prism UI. There is not another apparent problem.

**Screenshots**
![Image of the error](https://i.imgur.com/YC0opLS.png)

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.44
dappmanager.dnp.dappnode.eth: 0.2.40, commit: 6838be01
https.dnp.dappnode.eth: 0.1.0
ipfs.dnp.dappnode.eth: 0.2.14
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.6
wireguard.dnp.dappnode.eth: 0.1.0
System info
dockerComposeVersion: 1.27.4
dockerServerVersion: 20.10.2
dockerCliVersion: 20.10.2
os: debian
versionCodename: buster
architecture: amd64
kernel: 4.19.0-13-amd64
Disk usage: 70%

**Additional context**

Pyrmont version: Version: 0.1.20 (v1.3.9 upstream)
And this happens not he relative version of Pyrsm too.

**Comment by dapplion** [comment]
Awesome find! Cause is here:

https://github.com/dappnode/DNP_DAPPMANAGER/blob/6838be01fbd24e346c8c6e8c6a2a0940afcd939e/packages/dappmanager/src/modules/chains/drivers/ethereum2Prysm.ts#L34-L35
