### ISSUE TITLE
Chain module must consider multi-service packages

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#782]
**Is your feature request related to a problem? Please describe.**

When the code of the chain object was created, the dappnode package does not use the multiservices. So they obtained the container IP, creating an array with the containers and selecting the first one. 
```
 const container = dnp.containers[0];  if (!container) throw Error("no container"); 
```

**Describe the solution you'd like**

It would be nice to check how many containers are in the package:
- There is one service: take the first one.
- there are more services: throw an error.

The main problem with this is dappmanager need to know the name of the service in case the package has more than 1 services.

**Comment by dapplion** [comment]
The manifest.chain property should be changed to:
```ts
chain?: ChainDriver | {
  preset: ChainDriver;
  service?: string;
  port?: number;
}
```

**Comment by pablomendezroyo** [comment]
Now manifest allows to define the chain service and port
