### ISSUE TITLE
Create `packagesEnvGet` function api call

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#784]
There are at least 2 functions that needs to read package enverionment variables:
- `wifiCredentialsGet`
- `httpsLocalProxyingGet` (https://github.com/dappnode/DNP_DAPPMANAGER/pull/783#pullrequestreview-666588144)

In order to not duplicate code would be useful to create a function to implement this action (read environment variable from compose file) into a function and call this function where needed. Take as an example `packageSetEnvironment` function

**Comment by dapplion** [comment]
This can already be done with

https://github.com/dappnode/DNP_DAPPMANAGER/blob/6838be01fbd24e346c8c6e8c6a2a0940afcd939e/packages/dappmanager/src/calls/packageGet.ts#L101-L104
