### ISSUE TITLE
Review all docs endpoints 

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#786]
- [x] Review all docs endpoints and update them to new documentation 
- [x] Remove/add new docs endpoints if needed

**Comment by dapplion** [comment]
Prefix all constants that are links to the docs with `docsUrl*`

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/791
