### ISSUE TITLE
VPN bridge daemon only if open vpn package present

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#794]
Since recent releases Open VPN package is no longer mandatory so it could be missing in dappnode, for this reason the daemon `startVpnBridgeDaemon` should be executed only when this package is present. Otherwise there will be unnecesary errors and daemon running

**Comment by pablomendezroyo** [comment]
@dapplion would you say it is safe to remove the vpnBridgeDaemon? seems like its long time ago since this daemon was added?

**Comment by dapplion** [comment]
> @dapplion would you say it is safe to remove the vpnBridgeDaemon? seems like its long time ago since this daemon was added?

Yeah, it's only purpose is to show detailed version data which is not longer necessary. Please remove it.
