### ISSUE TITLE
Review Wireguard credentials display in UI

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#808]
**Describe the bug**

Currently we show the entire config, which is a bit unnecessary. We should not show the entire file immediatelly

**Proposed solution**

1. Add a button "Download something" that downloads the file with a proper name
2. Move buttons on top of the plain config display
3. (maybe) hide the plain config initially and add a "Show something" button that toggles the plain config view

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/813
