### ISSUE TITLE
UPnP ports scan - huge error

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#816]
**Describe the bug**

When running an UPnP scan and it breaks the error display is huge, breaking the ui layout.

**To Reproduce**

**Expected behavior**

**Screenshots**

@pablomendezroyo add screenshot please

**DAppNode version:**

- Package version: 
- OS: 
- Browser 

**Additional context**

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/814
