### ISSUE TITLE
Links in "Community" section must open in a new tab

### ISSUE THREAD

**Issue by Pol-Lanski** [dappnode/DNP_DAPPMANAGER#820]
**Describe the bug**

Links in "Community" section currently open in the same tab, kicking the user out of the DAppNodeUI. A better option is to open in a new tab so users can return to DAppNode without friction. 

**To Reproduce**

DAppManager 0.2.41 -> Go to Community Tab -> Click on links. 

**Expected behavior**

Links clicked should open in a new tab.

**Comment by dapplion** [comment]
@pablomendezroyo Use `newTabProps` like here
https://github.com/dappnode/DNP_DAPPMANAGER/blob/85e2b4cf9d0f3f321c1b623fe030a0ce8770dc87/packages/admin-ui/src/pages/packages/components/Info/Links.tsx#L23

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/826
