### ISSUE TITLE
New http endpoint to expose the "fullNode" selected by the user

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#824]
User chooses between full node, remote and light client as one of the dappnode settings.

If selection is full Node then dappmanager should expose this choice as an API endpoint so other dappnode packages know which is the default RPC endpoint used by its dappnode.

An example of necessity is https://github.com/dappnode/DAppNodePackage-rotki.dnp.dappnode.eth/issues/1

**Comment by dapplion** [comment]
Maybe we can expose the fullnode.dappnode target through `GLOBAL_ENVS`

**Comment by pablomendezroyo** [comment]
> Maybe we can expose the fullnode.dappnode target through `GLOBAL_ENVS`

sounds good

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/832
