### ISSUE TITLE
UI crashes when trying to install package onto LVM volume

### ISSUE THREAD

**Issue by TripleSpeeder** [dappnode/DNP_DAPPMANAGER#837]
**Describe the bug**

**Precondition**
Have a LVM volume mounted somewhere. In my case I have `/dev/mapper/raid_vg-raid_lv` mounted at `/mnt/raid/`. Output of `mount` command:
`/dev/mapper/raid_vg-raid_lv on /mnt/raid type ext4 (rw,relatime,errors=remount-ro,stripe=2)`

**To Reproduce**

1. bootstrap a minimal package: `dappnodesdk init`
2. Add `setup-wizard.yml` with the following contents:
```
version: "2"
fields:
  - id: mountpoints
    title: Mountpoints
    description: Set mountpoints
    target:
      type: allNamedVolumesMountpoint
``` 
3. build package: `dappnodesdk build`
4. Click on installation link

**Expected behavior**
Setup wizard should appear where the user can select the Mountpoint. Selection options should include default `Host` and my new `/mnt/raid`.

** Observed behaviour**
UI shows Error "Something went wrong".
DappManager logs the following error:
```
ERROR [api/logger:34] RPC error mountpointsGet SyntaxError: Unexpected token b in JSON at position 180
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/usr/src/app/webpack:/src/modules/hostScripts/scripts/mountpoints.ts:37:16)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/index.js:177156:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/754478/124589522-5fc37500-de5a-11eb-8f9f-ffa641eb3eef.png)

**DAppNode version:**

Core DAppNode Packages versions
bind.dnp.dappnode.eth: 0.2.6
core.dnp.dappnode.eth: 0.2.47
dappmanager.dnp.dappnode.eth: 0.2.42, branch: v0.2.43, commit: ec541936
https.dnp.dappnode.eth: 0.1.1
ipfs.dnp.dappnode.eth: 0.2.14
vpn.dnp.dappnode.eth: 0.2.8, commit: f9a8743e
wifi.dnp.dappnode.eth: 0.2.7
System info
dockerComposeVersion: 1.25.5
dockerServerVersion: 20.10.2
dockerCliVersion: 20.10.2

**Additional context**
Root cause of the problem is the hostScript `detect_fs.sh`. It tries to access `sys/class/block/$(partition)`. Since the LVM device does not appear at `/sys/class/block/...` the script throws an error.
See https://github.com/dappnode/DNP_DAPPMANAGER/blob/057b1eee877b9bc19c2fee9593cbbcd5de46a2e2/packages/dappmanager/hostScripts/detect_fs.sh#L16

**Comment by dapplion** [comment]
@pablomendezroyo Could you review the handling of mountpoints from the script? At least we should
- Add a JSON schema and validate the returned output from the script
- Figure out why the UI crashed due to bad data
