### ISSUE TITLE
Consider disable OOM (OutOfMemory) in core packages

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#843]
## New feature
The default behaviour in linux:

_By default, if an out-of-memory (OOM) error occurs, the kernel kills processes in a container_

Consider adding the option `--oom-kill-disable--` to core packages (specially in dappmanager and connectivity packages such as wifi or VPN to keep allowing the acces to the UI):

_To change this behavior, use the --oom-kill-disable option. Only disable the OOM killer on containers where you have also set the -m/--memory option. If the -m flag is not set, the host can run out of memory and the kernel may need to kill the host system’s processes to free memory._

This implementation should take into account to recognize when this situation happened to aler the user

## Benefits
- Prevent dappnode from totally crash
- Dappnode more resilient

## Concerns
- Research

SOURCE: https://docs.docker.com/config/containers/resource_constraints/

**Comment by dapplion** [comment]
Strongly disagree here. All packages you mention DAPPMANAGER, VPN, WIFI should have extremely low memory footprints. If the memory is too high it means there's a leak, so using that option will kill the entire node. Otherwise, if the host kills and restart the DAPPMANAGER the problem may fix itself, since the leak gets reseted.

Important: Have a you seen a memory leak in any of those packages? If so, please open a dedicated issue and let's work on it.

**Comment by pablomendezroyo** [comment]
> Strongly disagree here. All packages you mention DAPPMANAGER, VPN, WIFI should have extremely low memory footprints. If the memory is too high it means there's a leak, so using that option will kill the entire node. Otherwise, if the host kills and restart the DAPPMANAGER the problem may fix itself, since the leak gets reseted.
> 
> Important: Have a you seen a memory leak in any of those packages? If so, please open a dedicated issue and let's work on it.

What would happen if the host kills dappmanager and not the docker process? user will loose connectivity to the DAppNode without having an idea of what happened. Also I do not see why it would fix by itself

**Comment by dapplion** [comment]
> What would happen if the host kills dappmanager and not the docker process? user will loose connectivity to the DAppNode without having an idea of what happened. Also I do not see why it would fix by itself

Is that possible? How can the host kill an internal process in a container without killing it's parent container process?

**Comment by pablomendezroyo** [comment]
> > What would happen if the host kills dappmanager and not the docker process? user will loose connectivity to the DAppNode without having an idea of what happened. Also I do not see why it would fix by itself
> 
> Is that possible? How can the host kill an internal process in a container without killing it's parent container process?

I would say that killing a child process does not mean that the parent will be killed and killing a parent process means to kill all the childs from that parent process

**Comment by dapplion** [comment]
> I would say that killing a child process does not mean that the parent will be killed and killing a parent process means to kill all the childs from that parent process

From my experience if the process 1 OOM in a container, the container restarts. Try it yourself

**Comment by pablomendezroyo** [comment]
Not suitable
