### ISSUE TITLE
Add Moloch and maybe Ledger? to the Icon's of supporters

### ISSUE THREAD

**Issue by GriffGreen** [dappnode/DNP_DAPPMANAGER#845]
<img width="190" alt="Screen Shot 2020-07-07 at 10 58 04 PM" src="https://user-images.githubusercontent.com/14945613/86842581-b3637d00-c0a5-11ea-99df-2d190957e02f.png">

**Comment by pablomendezroyo** [comment]
@Pol-Lanski do we have a final idea of what icons should be placed now?

**Comment by pablomendezroyo** [comment]
Implemented
