### ISSUE TITLE
Requesting tooltips in the UI

### ISSUE THREAD

**Issue by ruvenni** [dappnode/DNP_DAPPMANAGER#846]
I think it would be great to have tooltips in the UI.

It would help users a lot to get to know what actions and functions can be triggered before clicking switches, buttons, and other elements in the UI.

A soft implementation would consist in just showing a mouse-over bubble with a text containing the tip associated with the element / function.

As a possible improvement to it, clicking on the bubble would take the user to the documentation regarding the action / function involved.

**Comment by pablomendezroyo** [comment]
Closing this due to lack of issue definition
