### ISSUE TITLE
Adopt Ofelia for easy cron job additions to packages

### ISSUE THREAD

**Issue by androolloyd** [dappnode/DNP_DAPPMANAGER#855]
**Is your feature request related to a problem? Please describe.**
Defining cron jobs for services is a paid, ofelia makes it easy, shipping ofelia repeatedly is a bad pattern

**Describe the solution you'd like**
DappNode to adopt ofelia or some similliar docker cron service

**Describe alternatives you've considered**
shipping your own cron jobs inside a wrapped docker image isn't ideal

**Additional context**
Some way to improve job automation on all dappnode packages.

**Comment by pablomendezroyo** [comment]
Wont implement.

For a shorthand solution, the geth will provide a workaround to do the prunning

@3alpha 👀
