### ISSUE TITLE
Add erigon as exposable service

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#856]
Erigon is another ETH 1 client and should be hardcoded in the dappmanager  to expose the RPC through the HTTPs portal in **system > network > https portal**

**Comment by dapplion** [comment]
@pablomendezroyo Please add this info in the Erigon package too!

**Comment by pablomendezroyo** [comment]
@dapplion Erigon package does not show sync progress on the UI. Any idea?

**Comment by pablomendezroyo** [comment]
> @pablomendezroyo Please add this info in the Erigon package too! Actually we must add the hardcoded services into their package's manifest to eventually remove the hardcoded data.

Where should be added that info? at `link>endpoint` ? 
```
"links": {
    "endpoint": "http://geth.dappnode:8545",
```

**Comment by dapplion** [comment]
> > @pablomendezroyo Please add this info in the Erigon package too! Actually we must add the hardcoded services into their package's manifest to eventually remove the hardcoded data.
> 
> Where should be added that info? at `link>endpoint` ?
> 
> ```
> "links": {
>     "endpoint": "http://geth.dappnode:8545",
> ```
> 
> https://github.com/dappnode/DAppNodePackage-Erigon/blob/c4e6fdb5060127550d2fa6a8d4c8155b44dbb9f6/dappnode_package.json#L16

No, see the docs https://docs.dappnode.io/developers/manifest-reference#exposable

**Comment by pablomendezroyo** [comment]
@dapplion 
Added at erigon package: https://github.com/dappnode/DAppNodePackage-Erigon/pull/12

Is it mandatory to add it right now on the dappmanager side, or is it enough to add it on the package side?

**Comment by dapplion** [comment]
> @dapplion
> Added at erigon package: [dappnode/DAppNodePackage-Erigon#12](https://github.com/dappnode/DAppNodePackage-Erigon/pull/12)
> 
> Is it mandatory to add it right now on the dappmanager side, or is it enough to add it on the package side?

We should never add anything else to the dappmanager regarding exposable services

**Comment by pablomendezroyo** [comment]
Implemented in erigon package
