### ISSUE TITLE
Add PID as a supported parameter on the docker-compose

### ISSUE THREAD

**Issue by eduadiez** [dappnode/DNP_DAPPMANAGER#857]
Erigon needs this command to be able to access directly to the database:

https://github.com/ledgerwatch/erigon/blob/89ab0615692130e757e4410b1be6b55a88f94726/docker-compose.yml#L44

So we should include it.

**Comment by dapplion** [comment]
Restrict to `service:****` only. Other values like `'host'` or `'container:***'` are too dangerous

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/pull/863
