### ISSUE TITLE
Consider creating a customizable dashboard with "plug-ins"

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#865]
For the current DAPPMANAGER version (v0.2.42) there are three main items shown in the dashboard:
- Machine stats
- Chains
- Packages updates

To improve user experience would be a nice to have a customizable dashboard where user can choose what to be shown on their dappnode dashboards

Things to bear in mind:
- Mandatory features: packages updates should be something to be shown in any case
- Add new features to select in the dashboard so the user can have more items to customize the dashboard

**Comment by dapplion** [comment]
Is there user demand for this? Sounds like a ton of UI work without a big return on investment

**Comment by pablomendezroyo** [comment]
agree
