### ISSUE TITLE
Duplicated mapping for host port XXX. Each host port can only be mapped once

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#886]
Since latest release (dappmanager V0.2.42), there is a bug in the UI that is causing the following error appear on the UI:
![image](https://user-images.githubusercontent.com/41727368/130975226-d1aee426-46dc-46f9-9d35-daadf9291ec4.png)

- [x] Determine if it is a bug in the UI and also backend bug
- [x] Determine if ports are been opened successfully

**Comment by pablomendezroyo** [comment]
@dapplion 
It is a bug that happens eventually depending on an unknown cause.
The ports are retrieved from the backend with `packagesGet`, which at the end get ports from `parseContainerInfo`:
https://github.com/dappnode/DNP_DAPPMANAGER/blob/4044dae46378707b78410b3c76e4b3b74780bcee/packages/dappmanager/src/modules/docker/list/parseContainerInfo.ts#L72

I see 2 workarounds:
1. Try to find out why ports are duplicated. Do you have any clue?
2. Set a sanitizer to not set duplicated ports at `parseContainerInfo`

**Comment by dapplion** [comment]
> Try to find out why ports are duplicated. Do you have any clue?

Would be worth it to investigate more, get the full JSON return from docker's API first and inspect it. Post it here as a .json file

> Set a sanitizer to not set duplicated ports at parseContainerInfo

Then let's do this too

**Comment by lodotek** [comment]
Any work around? This seems to also prevent me from adding any port mappings :-(

**Comment by lodotek** [comment]
Is there any way to remove a package and preserve the data containers (ie chaindata/blocks) then reinstall the package and reattach the data volumes?

**Comment by lodotek** [comment]
I'm starting to regret not going bare metal :-(

**Comment by pablomendezroyo** [comment]
> Any work around? This seems to also prevent me from adding any port mappings :-(
hey! yes, this issue will be fixed in the next release. This issue should not prevent you from adding port mappings, its just a UIX bug





> Is there any way to remove a package and preserve the data containers (ie chaindata/blocks) then reinstall the package and reattach the data volumes?

Yes there is, when removing a package you will be asked to remove or not volumes. If you want to preserve them, just select the option of not removing them

**Comment by lodotek** [comment]
> > Any work around? This seems to also prevent me from adding any port mappings :-(
> 
> 
> hey! yes, this issue will be fixed in the next release. This issue should not prevent you from adding port mappings, its just a UIX bug
> actually, I am unable to add port mappings, seemingly due to this bug.
> 
> > Is there any way to remove a package and preserve the data containers (ie chaindata/blocks) then reinstall the package and reattach the data volumes?
> 
> Yes there is, when removing a package you will be asked to remove or not volumes. If you want to preserve them, just select the option of not removing them

But what about when reinstalling the package, how do you get it to use the orphaned data volumes?

**Comment by alexpeterson91** [comment]
> 
> But what about when reinstalling the package, how do you get it to use the orphaned data volumes?

As long as you use don't change the container's data volume path then the volumes stay in the same default location with the same volume names but instead of creating new volumes it loads the ones already there, same volume name and location/path so it sees it the same as an update does, just loads it up.

**Comment by lodotek** [comment]
I almost forgot about this existing ticket that I already found. Has there been any progress in a fix yet by chance?
Or at least is there a way to ensure my custom modifications (to the docker-compose.yml file of packages where I had to add a custom mapping) do not get overwritten when packages get updated?

**Comment by pacrob** [comment]
> 

It is preventing adding port mappings. Any ETA on your new release?

**Comment by JHGrove3** [comment]
This is preventing me from changing the ports on my 2nd DAppNode, which is holding up testing on the process.

Thanks for prioritizing it, guys.

**Comment by abrileroux** [comment]
Rather frustrating issue... Would be great if it could get looked at please!
