### ISSUE TITLE
Add an easy way to download logs from avahi

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#897]
**Is your feature request related to a problem? Please describe.**

Some users have experimented with errors with avahi or local network features. Currently, we need the log information to check what can be the problem but the process which is needed to get the logs of avahi is not user-friendly. The user has to access the file  /usr/src/dappnode/logs/avahi_daemon.log using the CLI. 

This feature makes it easier for the user to collect data that is useful to approach the problem and we only have to indicate what part of the UI the user should click to obtain the data.

**Describe the solution you'd like**

It would be a good idea to include a button in the local network section which let the user download the logs, this button could be always visible or only show it in case there was an error.

**Comment by pablomendezroyo** [comment]
Yeah, this would be a really nice to have.

Actually there are more than 1 log file interesting from the support point of view:
- `avahi.log`
- `iso_install.log`
- `dappnode_install.log`
- `security-updates.log`
- `docker-updates.log`
....

What do you think of having just one place to serve all of them?

https://github.com/dappnode/DNP_DAPPMANAGER/issues/753

**Comment by dapplion** [comment]
> Yeah, this would be a really nice to have.
> 
> Actually there are more than 1 log file interesting from the support point of view:
> 
>     * `avahi.log`
> 
>     * `iso_install.log`
> 
>     * `dappnode_install.log`
> 
>     * `security-updates.log`
> 
>     * `docker-updates.log`
>       ....
> 
> 
> What do you think of having just one place to serve all of them?
> 
> #753

Yeah the easier the better

**Comment by pablomendezroyo** [comment]
Closed by https://github.com/dappnode/DNP_DAPPMANAGER/issues/753
