### ISSUE TITLE
Increase docker timeout for dappmanager container

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#945]
Right now the docker timeout is not enough to docker down the container https://github.com/dappnode/DNP_DAPPMANAGER/blob/7b9ad9ad556a24875ed222bd07fec2c9d3e8c568/packages/dappmanager/src/index.ts#L118

Add to the docker-compose the following to increase the docker timeout
```
   stop_signal: SIGINT
   stop_grace_period: 2m
```

- Determine the ideal timeout for the dappmanager

cc: @3alpha

**Comment by dapplion** [comment]
@pablomendezroyo What is the DAPPMANAGER doing that requires so much time?

**Comment by pablomendezroyo** [comment]
> @pablomendezroyo What is the DAPPMANAGER doing that requires so much time?

I have no idea, this issue has been there already for a while, seems like the SIGNIT signal does not work at all. We should do tests by increasing the timeout an checking what is the average timeout to get it down

Also we could check the processes inside the dappmanager container before, during and after the compose down

**Comment by dapplion** [comment]
@pablomendezroyo The DAPPMANAGER will require infinite timeout because it doesn't support a gracefull shutdown. You should implement first a gracefull shutdown, **only then** consider incrementing the timeout with a good justification.

**Comment by pablomendezroyo** [comment]
closed by https://github.com/dappnode/DNP_DAPPMANAGER/issues/665
