### ISSUE TITLE
Allow `apt update && apt-upgrade` from the UI

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#946]
There should be a host script that executes `apt update && apt upgrade` in the dappnode host to be executed on demand by the user directly from the UI. Aspects to consider:
- Check docker installation method (sources list or pkg): if sources list then temporary remove docker from the sources list for the update
- ?

cc: @dapplion @3alpha @alexpeterson91 @tropicar

**Comment by 3alpha** [comment]
I like this feature. We should limit ourselves to `apt upgrade` since we are using Debian which has long support period for each version.

**Comment by alexpeterson91** [comment]
Agreed users have been looking for a safe way to upgrade their OS without breaking dappnode. This will be well received.

**Comment by 3alpha** [comment]
Related to #695.
