### ISSUE TITLE
[Network range migration] Connect all DAppNode packages to the two docker networks

### ISSUE THREAD

**Issue by 3alpha** [dappnode/DNP_DAPPMANAGER#951]
# Intro 
Currently, DAppNode internally uses 172.33.0.0/16 network range which is designated as public. It would be good to move away from that range so that any issues arising from that are avoided.

- private network name: `dnprivate_network`
- private network range: `10.20.0.0/24`

Since DAppNode is highly modular system, migration will have to be done in multiple steps:
- **Connect all DAppNode packages to the two docker networks**
  - docker connect immediately on start + update the compose of the two issue
- Upgrade DNS resolver to use new network range
- Upgrade all packages that serve as access methods to the new range
- Test
- Test
- Remove old network

This issue concerns step one which will be starting point for all others steps.
# Features expected

DAppManager connects itself and all other packages to the new docker network in the same manner it connects it self to the existing `dncore_network`.

**Comment by alexpeterson91** [comment]
10.20.0.0/24 will be the new range correct? the one already baked into wireguard?

**Comment by 3alpha** [comment]
That is the plan, yes. Maybe we could've chosen block wiser both in terms of size and location.

**Comment by MysticRyuujin** [comment]
Why not either a) drop down to `172.32.0.0/16` or b) use a /16 off the 10.20.0.0?

Heck even better, make it configurable on initial setup for those of us with real networks where we might already use these ranges?

**Comment by alexpeterson91** [comment]
Making it configurable would involve a lot of work as it’s all hardcoded as is. It’s gonna be a few months just to change it to a new range. Making it user configurable would require a lot more work and make troubleshooting far more difficult. But we can explore that route i suppose.

**Comment by pablomendezroyo** [comment]
Another thing very important to take into account is that when moving to the new docker network `dnprivate_network`, the BIND container will have a different container IP than the current one `172.33.1.2`. This IP is used in all the packages docker-compose files in the compose key **dns**

**Comment by pablomendezroyo** [comment]
IP range migration already implemented! needs to be published
