### ISSUE TITLE
Review chain cards 

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#954]
Chain cards do not work properly sometimes, giving errors or even false errors or false status of the chain which generates unnecessary support.

The code to retrieve chain status must be high quality and deep tested.

- [ ] Consider implementing integration tests with remotes nodes for each chain
- [ ] Consider only rendering the card when the package is in the latest version to avoid version missmatching

**Comment by dapplion** [comment]
> Consider only rendering the card when the package is in the latest version to avoid version miss-matching

This is a good one, and would incentivize updating

**Comment by pablomendezroyo** [comment]
After the merge, the execution client sync progress status is hard to determine:
- Consider determining it as a binary status: synced / not synced by using another UIX element and not a progress bar
- Consider adding to the chain card the number of peers that the node is connected to
- Consider showing the version in the chain card
- Consider showing slot and epoch

**Comment by pablomendezroyo** [comment]
Execution client:
```
{
  syncing: boolean  // https://ethereum.org/es/developers/docs/apis/json-rpc/#eth_syncing
  startingBlock?: number,
  currentBlock?: number,
  numberOfPeers: number // https://ethereum.org/es/developers/docs/apis/json-rpc/#net_peercount ,
  chainId: number,
```

**Comment by dsimog01** [comment]
We could have an optional field called networkName that could help us to order the chains by network and also for EL and CL clients we could have, for example, an icon or sign in the top right part that identifies the chain/network of the package
