### ISSUE TITLE
Consider upgrading dockerode library version

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#957]
- Current dockerode version in dappmanager: **3.2.2** (2 years ago)**
- Latest upstream dockerode version: **3.3.1** (5 months ago)
https://www.npmjs.com/package/dockerode

Consider upgrading the dockerode version to stay up to date with latest docker features addded:
- [ ] Upgrade dockerode version
- [ ] Research for breaking tests in the dappmanager and fix them
- [ ] Deep test docker functionalities in the dappmanager

**Comment by dapplion** [comment]
Nothing substantial has changed really, here you can see the diff https://github.com/apocas/dockerode/compare/v3.2.1...v3.3.1

**Comment by pablomendezroyo** [comment]
oh this is great, then docker API calls are often wrong typed in dockerode library, we should review it. An example is `Dockerode.ImageInfo`
