### ISSUE TITLE
Diagnosis tool

### ISSUE THREAD

**Issue by dapplion** [dappnode/DNP_DAPPMANAGER#97]
Maybe it's a good idea to have a string of commands to automatically verify DAppNode's stats so support can move on quicker.
- Get list of installed versions
```
docker ps
```
- Get the remaining space on DAppNode
```
df -h
```
- Get docker and docker-compose versions
```
docker -v
docker-compose -v
docker exec -it DAppNodeCore-dappmanager.dnp.dappnode.eth docker -v
```
- Check dappmanager's paths
```
docker exec -it DAppNodeCore-dappmanager.dnp.dappnode.eth ls dnp_repo
docker exec -it DAppNodeCore-dappmanager.dnp.dappnode.eth ls DNCORE
```

**Comment by Shelpin** [comment]
Great job!!!  let us keep it going with new features, could be useful to have chains and status as an option as "Add chain data"....

**Comment by dapplion** [comment]
Yes! Will progress this issue this week

**Comment by Shelpin** [comment]
Continuing improvement of  the tool but closing issue
