### ISSUE TITLE
Core update should not omit aggregate dependency errors

### ISSUE THREAD

**Issue by pablomendezroyo** [dappnode/DNP_DAPPMANAGER#985]
## Context
Core update is done through the DNP_CORE which hash a list of dependencies with the core packages. It uses core packages as aggregate dependencies of the core package, however there are a few edge cases.

Core updates are critical and must not fail in any case

## Bug
If the dependency ENS does not exist it is thrown an error. But if the dependencies ENS exist and there is an error fetching thos dependencies it is been assumed as none dependencies (see [ref](https://github.com/dappnode/DNP_DAPPMANAGER/blob/56c66f119c9288c34c48aeb69505c5d13e7c12a2/packages/dappmanager/src/modules/dappGet/aggregate/aggregateDependencies.ts#L65))

This behaviour may not be expected specially for the DNP_CORE used to trigger core updates.

It should be done something like 
```
const dependencies = await dappGetFetcher
        .dependencies(name, version)
        .then(sanitizeDependencies)
        .catch((e: Error) => {
          logs.warn(
            `Error fetching ${name}@${version} dependencies (assuming it has none)`,
            e
          );
 
NEW  =>  if(isCoreUpdate) throw Error("Error fetching mandatory core update dependencies", e)
   
          return emptyDeps;
        });
```

**Comment by dapplion** [comment]
I think dappGet should always error if dependencies can not be fetched. Currently all packages that have a dependency, it is required so this fallback is really dangerous.
