### ISSUE TITLE
Add an option to reserve an ip for a container package

### ISSUE THREAD

**Issue by tropicar** [dappnode/DNP_DAPPMANAGER#987]
**Is your feature request related to a problem? Please describe.**

Some users have declared that packages like monero change the IP container every time reboot cycle. This can be annoying because you have to modify the endpoint to which you are connecting to.

**Describe the solution you'd like**
Would it be possible to reserve the private IP for a selected package? For example, Monero package has 192.33.0.12 internal IP, add a button on the network section or systems(Reserve IPs, title example) where you can indicate the IP is for some package same.

I don't know if this feature is possible, or how simple is to implement but maybe can be useful for some users.

**Comment by dapplion** [comment]
Why not use the package domain? `monero.dappnode`

**Comment by alexpeterson91** [comment]
its not worth it to anything with the IP address until we finish the migration to the new subnet right? just keep it on the table till we redo the entire docker subnet.

**Comment by 3alpha** [comment]
I don't see any potential issues, but also I don't see any point in implementing this. As you said, `monero.dappnode` or `whatever.dappnode` should always be working, and if it isn't we should focus on that.
